/*
 * JSP generated by Resin 2.1.12 (built Tue Dec  9 14:58:25 PST 2003)
 */

package _management;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.eurocash.data.management.customer.CustomerBean;

public class _customerUpdate__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=iso-8859-1");
    org.apache.taglibs.standard.tag.el.core.ImportTag _jsp_tag0 = null;
    org.apache.taglibs.standard.tag.el.core.OutTag _jsp_tag1 = null;
    org.apache.taglibs.standard.tag.el.core.ForEachTag _jsp_tag2 = null;
    org.apache.taglibs.standard.tag.el.core.OutTag _jsp_tag3 = null;
    org.apache.taglibs.standard.tag.el.core.IfTag _jsp_tag4 = null;
    org.apache.taglibs.standard.tag.el.core.OutTag _jsp_tag7 = null;
    org.apache.taglibs.standard.tag.el.core.IfTag _jsp_tag5 = null;
    org.apache.taglibs.standard.tag.el.core.OutTag _jsp_tag6 = null;
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      com.eurocash.data.administration.agency.AgenciesBean agenciesBean;
      synchronized (application) {
        agenciesBean = (com.eurocash.data.administration.agency.AgenciesBean) application.getAttribute("agenciesBean");
        if (agenciesBean == null) {
          agenciesBean = new com.eurocash.data.administration.agency.AgenciesBean();
          application.setAttribute("agenciesBean", agenciesBean);
        }
      }
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      com.eurocash.data.type.TypeListBean typeListBean;
      synchronized (application) {
        typeListBean = (com.eurocash.data.type.TypeListBean) application.getAttribute("typeListBean");
        if (typeListBean == null) {
          typeListBean = new com.eurocash.data.type.TypeListBean();
          application.setAttribute("typeListBean", typeListBean);
        }
      }
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      com.eurocash.data.mapping.form.FormMappingObject customerUpdateForm;
      synchronized (session) {
        customerUpdateForm = (com.eurocash.data.mapping.form.FormMappingObject) session.getAttribute("customerUpdateForm");
        if (customerUpdateForm == null) {
          throw new java.lang.InstantiationException("`com.eurocash.data.mapping.form.FormMappingObject' has no public zero-arg constructor");
        }
      }
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      if (_jsp_tag0 == null) {
        _jsp_tag0 = new org.apache.taglibs.standard.tag.el.core.ImportTag();
        _jsp_tag0.setPageContext(pageContext);
        _jsp_tag0.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag0.setUrl("/include/jsp/menu.jsp");
      javax.servlet.jsp.JspWriter _jsp_writer1 = out;
      try {
        _jsp_tag0.doStartTag();
        _jsp_tag0.setBodyContent(null);
        int _jsp_endTagVar3 = _jsp_tag0.doEndTag();
        if (_jsp_endTagVar3 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
          return;
        } catch (Throwable t) {
        pageContext.setWriter(_jsp_writer1);
        out = _jsp_writer1;
          _jsp_tag0.doCatch(t);
        } finally {
          _jsp_tag0.doFinally();
        }
        pageContext.write(_jsp_string3, 0, _jsp_string3.length);
        out.print((CustomerBean.STE_CIVILITY));
        pageContext.write(_jsp_string4, 0, _jsp_string4.length);
        out.print((CustomerBean.SARL_CIVILITY));
        pageContext.write(_jsp_string5, 0, _jsp_string5.length);
        out.print((CustomerBean.SCI_CIVILITY));
        pageContext.write(_jsp_string6, 0, _jsp_string6.length);
        _jsp_tag0.setUrl("/include/jsp/header.jsp");
        javax.servlet.jsp.JspWriter _jsp_writer5 = out;
        try {
          _jsp_tag0.doStartTag();
          _jsp_tag0.setBodyContent(null);
          int _jsp_endTagVar7 = _jsp_tag0.doEndTag();
          if (_jsp_endTagVar7 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
            return;
          } catch (Throwable t) {
          pageContext.setWriter(_jsp_writer5);
          out = _jsp_writer5;
            _jsp_tag0.doCatch(t);
          } finally {
            _jsp_tag0.doFinally();
          }
          pageContext.write(_jsp_string7, 0, _jsp_string7.length);
          _caucho_expr_0.print(pageContext.getWriteStream(), pageContext, true);
          pageContext.write(_jsp_string8, 0, _jsp_string8.length);
          if (_jsp_tag2 == null) {
            _jsp_tag2 = new org.apache.taglibs.standard.tag.el.core.ForEachTag();
            _jsp_tag2.setPageContext(pageContext);
            _jsp_tag2.setParent((javax.servlet.jsp.tagext.Tag) null);
            _jsp_tag2.setVarStatus("status");
          }

          _jsp_tag2.setVar("attribute");
          _jsp_tag2.setItems("${typeListBean.hashMap['civility']}");
          javax.servlet.jsp.JspWriter _jsp_writer9 = out;
          try {
            int _jspEval10 = _jsp_tag2.doStartTag();
            if (_jspEval10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
              do {
                pageContext.write(_jsp_string9, 0, _jsp_string9.length);
                _caucho_expr_1.print(pageContext.getWriteStream(), pageContext, true);
                pageContext.write(_jsp_string10, 0, _jsp_string10.length);
                if (_caucho_expr_2.evalBoolean(pageContext)) {
                  pageContext.write(_jsp_string11, 0, _jsp_string11.length);
                }
                pageContext.write(_jsp_string12, 0, _jsp_string12.length);
                _caucho_expr_3.print(pageContext.getWriteStream(), pageContext, true);
                pageContext.write(_jsp_string13, 0, _jsp_string13.length);
              } while (_jsp_tag2.doAfterBody() == javax.servlet.jsp.tagext.IterationTag.EVAL_BODY_AGAIN);
            }
            } catch (Throwable t) {
            pageContext.setWriter(_jsp_writer9);
            out = _jsp_writer9;
              _jsp_tag2.doCatch(t);
            } finally {
              _jsp_tag2.doFinally();
            }
            pageContext.write(_jsp_string14, 0, _jsp_string14.length);
            _caucho_expr_4.print(pageContext.getWriteStream(), pageContext, true);
            pageContext.write(_jsp_string15, 0, _jsp_string15.length);
            if (_caucho_expr_5.evalBoolean(pageContext)) {
              pageContext.write(_jsp_string16, 0, _jsp_string16.length);
              _caucho_expr_6.print(pageContext.getWriteStream(), pageContext, true);
              pageContext.write(_jsp_string17, 0, _jsp_string17.length);
            }
            pageContext.write(_jsp_string18, 0, _jsp_string18.length);
            _caucho_expr_7.print(pageContext.getWriteStream(), pageContext, true);
            pageContext.write(_jsp_string15, 0, _jsp_string15.length);
            if (_caucho_expr_8.evalBoolean(pageContext)) {
              pageContext.write(_jsp_string16, 0, _jsp_string16.length);
              _caucho_expr_9.print(pageContext.getWriteStream(), pageContext, true);
              pageContext.write(_jsp_string17, 0, _jsp_string17.length);
            }
            pageContext.write(_jsp_string19, 0, _jsp_string19.length);
            _caucho_expr_10.print(pageContext.getWriteStream(), pageContext, true);
            pageContext.write(_jsp_string20, 0, _jsp_string20.length);
            _caucho_expr_11.print(pageContext.getWriteStream(), pageContext, true);
            pageContext.write(_jsp_string21, 0, _jsp_string21.length);
            _caucho_expr_12.print(pageContext.getWriteStream(), pageContext, true);
            pageContext.write(_jsp_string22, 0, _jsp_string22.length);
            _caucho_expr_13.print(pageContext.getWriteStream(), pageContext, true);
            pageContext.write(_jsp_string23, 0, _jsp_string23.length);
            _caucho_expr_14.print(pageContext.getWriteStream(), pageContext, true);
            pageContext.write(_jsp_string24, 0, _jsp_string24.length);
            _caucho_expr_15.print(pageContext.getWriteStream(), pageContext, true);
            pageContext.write(_jsp_string25, 0, _jsp_string25.length);
            _jsp_tag2.setVar("agency");
            _jsp_tag2.setItems("${agenciesBean.agenciesList}");
            javax.servlet.jsp.JspWriter _jsp_writer12 = out;
            try {
              int _jspEval13 = _jsp_tag2.doStartTag();
              if (_jspEval13 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  pageContext.write(_jsp_string9, 0, _jsp_string9.length);
                  _caucho_expr_16.print(pageContext.getWriteStream(), pageContext, true);
                  pageContext.write(_jsp_string10, 0, _jsp_string10.length);
                  if (_caucho_expr_17.evalBoolean(pageContext)) {
                    _caucho_expr_18.print(pageContext.getWriteStream(), pageContext, true);
                  }
                  pageContext.write(_jsp_string12, 0, _jsp_string12.length);
                  _caucho_expr_19.print(pageContext.getWriteStream(), pageContext, true);
                  pageContext.write(_jsp_string13, 0, _jsp_string13.length);
                } while (_jsp_tag2.doAfterBody() == javax.servlet.jsp.tagext.IterationTag.EVAL_BODY_AGAIN);
              }
              } catch (Throwable t) {
              pageContext.setWriter(_jsp_writer12);
              out = _jsp_writer12;
                _jsp_tag2.doCatch(t);
              } finally {
                _jsp_tag2.doFinally();
              }
              pageContext.write(_jsp_string26, 0, _jsp_string26.length);
            } catch (java.lang.Throwable _jsp_e) {
              pageContext.handlePageException(_jsp_e);
            } finally {
              if (_jsp_tag0 != null)
                _jsp_tag0.release();
              if (_jsp_tag1 != null)
                _jsp_tag1.release();
              if (_jsp_tag2 != null)
                _jsp_tag2.release();
              if (_jsp_tag3 != null)
                _jsp_tag3.release();
              if (_jsp_tag4 != null)
                _jsp_tag4.release();
              if (_jsp_tag5 != null)
                _jsp_tag5.release();
              if (_jsp_tag6 != null)
                _jsp_tag6.release();
              if (_jsp_tag7 != null)
                _jsp_tag7.release();
              JspFactory.getDefaultFactory().releasePageContext(pageContext);
            }
          }

          private com.caucho.java.LineMap _caucho_line_map;
          private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

          public boolean _caucho_isModified()
          {
            if (_caucho_isDead)
              return true;
            if (com.caucho.util.CauchoSystem.getVersionId() != -2089842223)
              return true;
            for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
              com.caucho.vfs.Depend depend;
              depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
              if (depend.isModified())
                return true;
            }
            return false;
          }

          public long _caucho_lastModified()
          {
            return 0;
          }

          public com.caucho.java.LineMap _caucho_getLineMap()
          {
            return _caucho_line_map;
          }

          public void destroy()
          {
              _caucho_isDead = true;
              super.destroy();
          }

          public void init(com.caucho.java.LineMap lineMap,
                           com.caucho.vfs.Path appDir)
            throws javax.servlet.ServletException
          {
            com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
            com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
            mergePath.addMergePath(appDir);
            mergePath.addMergePath(resinHome);
            mergePath.addClassPath(getClass().getClassLoader());
            _caucho_line_map = new com.caucho.java.LineMap("_customerUpdate__jsp.java", "/management/customerUpdate.jsp");
            _caucho_line_map.add(1, 1);
            _caucho_line_map.add(1, 35);
            _caucho_line_map.add(3, 36);
            _caucho_line_map.add(5, 37);
            _caucho_line_map.add(6, 46);
            _caucho_line_map.add(7, 55);
            _caucho_line_map.add(23, 63);
            _caucho_line_map.add(23, 74);
            _caucho_line_map.add(29, 85);
            _caucho_line_map.add(30, 87);
            _caucho_line_map.add(31, 89);
            _caucho_line_map.add(48, 91);
            _caucho_line_map.add(48, 96);
            _caucho_line_map.add(55, 107);
            _caucho_line_map.add(66, 109);
            _caucho_line_map.add(66, 123);
            _caucho_line_map.add(67, 126);
            _caucho_line_map.add(67, 130);
            _caucho_line_map.add(74, 142);
            _caucho_line_map.add(75, 144);
            _caucho_line_map.add(76, 146);
            _caucho_line_map.add(81, 150);
            _caucho_line_map.add(82, 152);
            _caucho_line_map.add(83, 154);
            _caucho_line_map.add(91, 158);
            _caucho_line_map.add(95, 160);
            _caucho_line_map.add(99, 162);
            _caucho_line_map.add(103, 164);
            _caucho_line_map.add(107, 166);
            _caucho_line_map.add(111, 168);
            _caucho_line_map.add(117, 170);
            _caucho_line_map.add(117, 177);
            _caucho_line_map.add(118, 180);
            _caucho_line_map.add(118, 181);
            _caucho_line_map.add(118, 184);
            com.caucho.vfs.Depend depend;
            depend = new com.caucho.vfs.Depend(appDir.lookup("management/customerUpdate.jsp"), 1087659656000L, 5897L);
            _caucho_depends.add(depend);
          }

          protected void _caucho_clearDepends()
          {
            _caucho_depends.clear();
          }
          private static com.caucho.el.Expr _caucho_expr_0 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("customerUpdateForm"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("id"));
          private static com.caucho.el.Expr _caucho_expr_1 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("attribute"), new com.caucho.el.StringLiteral("key"));
          private static com.caucho.el.Expr _caucho_expr_2 =
            new com.caucho.el.EqExpr(6, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("attribute"), new com.caucho.el.StringLiteral("key")), new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("customerUpdateForm"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("civilityId")));
          private static com.caucho.el.Expr _caucho_expr_3 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("attribute"), new com.caucho.el.StringLiteral("value"));
          private static com.caucho.el.Expr _caucho_expr_4 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("customerUpdateForm"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("lastName"));
          private static com.caucho.el.Expr _caucho_expr_5 =
            new com.caucho.el.UnaryExpr(14, new com.caucho.el.UnaryExpr(16, new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("customerUpdateForm"), new com.caucho.el.StringLiteral("errorFields")), new com.caucho.el.StringLiteral("lastName"))));
          private static com.caucho.el.Expr _caucho_expr_6 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("customerUpdateForm"), new com.caucho.el.StringLiteral("errorFields")), new com.caucho.el.StringLiteral("lastName"));
          private static com.caucho.el.Expr _caucho_expr_7 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("customerUpdateForm"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("firstName"));
          private static com.caucho.el.Expr _caucho_expr_8 =
            new com.caucho.el.UnaryExpr(14, new com.caucho.el.UnaryExpr(16, new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("customerUpdateForm"), new com.caucho.el.StringLiteral("errorFields")), new com.caucho.el.StringLiteral("firstName"))));
          private static com.caucho.el.Expr _caucho_expr_9 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("customerUpdateForm"), new com.caucho.el.StringLiteral("errorFields")), new com.caucho.el.StringLiteral("firstName"));
          private static com.caucho.el.Expr _caucho_expr_10 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("customerUpdateForm"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("address"));
          private static com.caucho.el.Expr _caucho_expr_11 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("customerUpdateForm"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("city"));
          private static com.caucho.el.Expr _caucho_expr_12 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("customerUpdateForm"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("postalCode"));
          private static com.caucho.el.Expr _caucho_expr_13 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("customerUpdateForm"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("phone"));
          private static com.caucho.el.Expr _caucho_expr_14 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("customerUpdateForm"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("cellPhone"));
          private static com.caucho.el.Expr _caucho_expr_15 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("customerUpdateForm"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("email"));
          private static com.caucho.el.Expr _caucho_expr_16 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agency"), new com.caucho.el.StringLiteral("id"));
          private static com.caucho.el.Expr _caucho_expr_17 =
            new com.caucho.el.EqExpr(6, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agency"), new com.caucho.el.StringLiteral("id")), new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("customerListForm"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("agencyId")));
          private static com.caucho.el.Expr _caucho_expr_18 =
            new com.caucho.el.StringLiteral("SELECTED");
          private static com.caucho.el.Expr _caucho_expr_19 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agency"), new com.caucho.el.StringLiteral("company"));

          private static byte []_jsp_string0;
          private static byte []_jsp_string8;
          private static byte []_jsp_string21;
          private static byte []_jsp_string22;
          private static byte []_jsp_string23;
          private static byte []_jsp_string1;
          private static byte []_jsp_string14;
          private static byte []_jsp_string15;
          private static byte []_jsp_string4;
          private static byte []_jsp_string18;
          private static byte []_jsp_string13;
          private static byte []_jsp_string11;
          private static byte []_jsp_string24;
          private static byte []_jsp_string9;
          private static byte []_jsp_string2;
          private static byte []_jsp_string5;
          private static byte []_jsp_string25;
          private static byte []_jsp_string16;
          private static byte []_jsp_string26;
          private static byte []_jsp_string17;
          private static byte []_jsp_string7;
          private static byte []_jsp_string19;
          private static byte []_jsp_string3;
          private static byte []_jsp_string6;
          private static byte []_jsp_string20;
          private static byte []_jsp_string10;
          private static byte []_jsp_string12;
          static {
            _jsp_string0 = "\n\n".getBytes();
            _jsp_string8 = "\">\n	\n		<br>\n				\n		<h1 class=\"title\">Clients&nbsp;&nbsp;:&nbsp;:&nbsp;&nbsp;Modification</h1>\n		\n		<div class=\"boxTitle\">&nbsp;&nbsp;Identit\u00e9: </div>\n			<div class=\"boxCol\">\n				<p class=\"boxField\">&nbsp;&nbsp;Civilit\u00e9 :</p>\n				<p class=\"boxInput\">\n					<select name=\"civilityId\" onchange=\"changeCivility();\">\n						".getBytes();
            _jsp_string21 = "\"></p>\n			</div>\n			<div class=\"boxCol\">\n				<p class=\"boxField\">&nbsp;&nbsp;Code Postal :</p>\n				<p class=\"boxInput\"><input type=\"text\" name=\"postalCode\" value=\"".getBytes();
            _jsp_string22 = "\"></p>\n			</div>\n			<div class=\"boxCol\">\n				<p class=\"boxField\">&nbsp;&nbsp;T\u00e9l\u00e9phone :</p>\n				<p class=\"boxInput\"><input type=\"text\" name=\"phone\" value=\"".getBytes();
            _jsp_string23 = "\"></p>\n			</div>\n			<div class=\"boxCol\">\n				<p class=\"boxField\">&nbsp;&nbsp;Portable :</p>\n				<p class=\"boxInput\"><input type=\"text\" name=\"cellPhone\" value=\"".getBytes();
            _jsp_string1 = "\n".getBytes();
            _jsp_string14 = "\n					</select>\n				</p>\n			</div>\n			<div class=\"boxCol\">\n				<p class=\"boxField\">&nbsp;&nbsp;Nom :</p>\n				<p class=\"boxInput\"><input type=\"text\" name=\"lastName\" value=\"".getBytes();
            _jsp_string15 = "\"></p>\n				".getBytes();
            _jsp_string4 = ";\n			var sarl_code = ".getBytes();
            _jsp_string18 = "\n			</div>\n			<div class=\"boxCol\" id=\"firstNameBox\">\n				<p class=\"boxField\">&nbsp;&nbsp;Pr\u00e9nom :</p>\n				<p class=\"boxInput\"><input type=\"text\" name=\"firstName\" value=\"".getBytes();
            _jsp_string13 = "</option>\n						".getBytes();
            _jsp_string11 = "SELECTED".getBytes();
            _jsp_string24 = "\"></p>\n			</div>\n			<div class=\"boxCol\">\n				<p class=\"boxField\">&nbsp;&nbsp;E-mail :</p>\n				<p class=\"boxInput\"><input type=\"text\" name=\"email\" value=\"".getBytes();
            _jsp_string9 = "\n						<option value=\"".getBytes();
            _jsp_string2 = "\n\n<?xml version=\"1\" encoding=\"ISO-8859-1\"?>\n<!DOCTYPE html PUBLIC \"- //w3c//DTD XHTML 1.0 Strict//EN\" \n\"http://www.w3.org/TR/xhtml11/DTD/xhtml11-strict.dtd\">\n\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n	<head>\n		<title>Modification client</title>\n		<link href=\"/include/style/styleAdd.css\" rel=\"stylesheet\" type=\"text/css\">\n		<link href=\"/include/style/global.css\" rel=\"stylesheet\" type=\"text/css\">\n		<link href=\"/include/style/header.css\" rel=\"stylesheet\" type=\"text/css\">\n		\n		<script src=\"/include/scripts/global.js\"></script>\n		\n		<!-- create dynamic menu -->\n		".getBytes();
            _jsp_string5 = ";\n			var sci_code = ".getBytes();
            _jsp_string25 = "\"></p>\n			</div>\n			<div class=\"boxCol\">\n				<p class=\"boxField\">&nbsp;&nbsp;Agence :</p>\n				<p class=\"boxInput\">\n					<select name=\"agencyId\" >\n						".getBytes();
            _jsp_string16 = "\n					<p class=\"boxError\"><img src=\"/include/pictures/warning.png\">&nbsp;&nbsp;&nbsp;".getBytes();
            _jsp_string26 = "\n					</select>\n				</p>\n			</div>\n		</div>\n		\n		<div class=\"boxAction\">\n			<a class=\"classicButtonGreen\" onclick=\"updateForm.submit();\">&nbsp;Valider&nbsp;</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n			<a class=\"classicButtonRed\" onclick=\"window.location.href = '/DomainActionServlet?domain=customer&action=list&subAction=init';\">&nbsp;Annuler&nbsp;</a>\n		</div>\n		\n		</form>\n	</body>\n</html>".getBytes();
            _jsp_string17 = "</p>\n				".getBytes();
            _jsp_string7 = "\n	\n		<form name=\"updateForm\" action=\"DomainActionServlet\" method=\"POST\">\n			<input type=\"hidden\" name=\"domain\" value=\"customer\">\n			<input type=\"hidden\" name=\"action\" value=\"update\">\n			<input type=\"hidden\" name=\"subAction\" value=\"ok\">\n	\n			<input type=\"hidden\" name=\"id\" value=\"".getBytes();
            _jsp_string19 = "\n			</div>\n		</div>\n		\n		<div class=\"boxTitle\">&nbsp;&nbsp;Coordonn\u00e9es: </div>\n			<div class=\"boxCol\">\n				<p class=\"boxField\">&nbsp;&nbsp;Adresse :</p>\n				<p class=\"boxInput\"><input type=\"text\" name=\"address\" value=\"".getBytes();
            _jsp_string3 = "\n	\n	</head>\n	\n	<script language=\"Javascript\">\n		function changeCivility() {\n			var ste_code = ".getBytes();
            _jsp_string6 = ";\n			var civility = document.addForm.civilityId.value;\n			\n			if (civility == company_code) {\n				/* hide the \"firstName\" box */\n				document.addForm.firstNameBox.style.visibility = \"hidden\";\n				document.addForm.firstName.value = \"\";\n			} else {\n				document.addForm.firstNameBox.style.visibility = \"show\";\n			}\n		}\n	\n	</script>	\n	\n	<body>\n	\n		<!-- display header : company logo + menu + user info -->\n		".getBytes();
            _jsp_string20 = "\"></p>\n			</div>\n			<div class=\"boxCol\">\n				<p class=\"boxField\">&nbsp;&nbsp;Ville :</p>\n				<p class=\"boxInput\"><input type=\"text\" name=\"city\" value=\"".getBytes();
            _jsp_string10 = "\" ".getBytes();
            _jsp_string12 = ">".getBytes();
          }
        }
