/*
 * JSP generated by Resin 2.1.12 (built Tue Dec  9 14:58:25 PST 2003)
 */

package _material;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _catalogueItemList__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=iso-8859-1");
    org.apache.taglibs.standard.tag.el.core.ImportTag _jsp_tag0 = null;
    org.apache.taglibs.standard.tag.el.core.ParamTag _jsp_tag16 = null;
    org.apache.taglibs.standard.tag.el.core.OutTag _jsp_tag1 = null;
    org.apache.taglibs.standard.tag.el.core.IfTag _jsp_tag2 = null;
    org.apache.taglibs.standard.tag.el.core.ForEachTag _jsp_tag3 = null;
    org.apache.taglibs.standard.tag.el.core.OutTag _jsp_tag4 = null;
    org.apache.taglibs.standard.tag.el.core.IfTag _jsp_tag5 = null;
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jsp_tag6 = null;
    org.apache.taglibs.standard.tag.el.core.WhenTag _jsp_tag7 = null;
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jsp_tag8 = null;
    org.apache.taglibs.standard.tag.el.core.ForEachTag _jsp_tag9 = null;
    org.apache.taglibs.standard.tag.el.core.OutTag _jsp_tag10 = null;
    org.apache.taglibs.standard.tag.el.core.IfTag _jsp_tag11 = null;
    org.apache.taglibs.standard.tag.el.core.OutTag _jsp_tag12 = null;
    org.apache.taglibs.standard.tag.el.core.ForEachTag _jsp_tag13 = null;
    org.apache.taglibs.standard.tag.el.core.IfTag _jsp_tag14 = null;
    org.apache.taglibs.standard.tag.el.core.OutTag _jsp_tag15 = null;
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      com.eurocash.data.ItemListBean catalogueItemListBean;
      synchronized (session) {
        catalogueItemListBean = (com.eurocash.data.ItemListBean) session.getAttribute("catalogueItemListBean");
        if (catalogueItemListBean == null) {
          catalogueItemListBean = new com.eurocash.data.ItemListBean();
          session.setAttribute("catalogueItemListBean", catalogueItemListBean);
        }
      }
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      com.eurocash.data.mapping.form.FormMappingObject catalogueItemListForm;
      synchronized (session) {
        catalogueItemListForm = (com.eurocash.data.mapping.form.FormMappingObject) session.getAttribute("catalogueItemListForm");
        if (catalogueItemListForm == null) {
          throw new java.lang.InstantiationException("`com.eurocash.data.mapping.form.FormMappingObject' has no public zero-arg constructor");
        }
      }
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      com.eurocash.data.administration.agency.AgenciesBean agenciesBean;
      synchronized (application) {
        agenciesBean = (com.eurocash.data.administration.agency.AgenciesBean) application.getAttribute("agenciesBean");
        if (agenciesBean == null) {
          agenciesBean = new com.eurocash.data.administration.agency.AgenciesBean();
          application.setAttribute("agenciesBean", agenciesBean);
        }
      }
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      com.eurocash.data.type.TypeListBean typeListBean;
      synchronized (application) {
        typeListBean = (com.eurocash.data.type.TypeListBean) application.getAttribute("typeListBean");
        if (typeListBean == null) {
          typeListBean = new com.eurocash.data.type.TypeListBean();
          application.setAttribute("typeListBean", typeListBean);
        }
      }
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      if (_jsp_tag0 == null) {
        _jsp_tag0 = new org.apache.taglibs.standard.tag.el.core.ImportTag();
        _jsp_tag0.setPageContext(pageContext);
        _jsp_tag0.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag0.setUrl("/include/jsp/menu.jsp");
      javax.servlet.jsp.JspWriter _jsp_writer1 = out;
      try {
        _jsp_tag0.doStartTag();
        _jsp_tag0.setBodyContent(null);
        int _jsp_endTagVar3 = _jsp_tag0.doEndTag();
        if (_jsp_endTagVar3 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
          return;
        } catch (Throwable t) {
        pageContext.setWriter(_jsp_writer1);
        out = _jsp_writer1;
          _jsp_tag0.doCatch(t);
        } finally {
          _jsp_tag0.doFinally();
        }
        pageContext.write(_jsp_string3, 0, _jsp_string3.length);
        _jsp_tag0.setUrl("/include/jsp/header.jsp");
        javax.servlet.jsp.JspWriter _jsp_writer5 = out;
        try {
          _jsp_tag0.doStartTag();
          _jsp_tag0.setBodyContent(null);
          int _jsp_endTagVar7 = _jsp_tag0.doEndTag();
          if (_jsp_endTagVar7 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
            return;
          } catch (Throwable t) {
          pageContext.setWriter(_jsp_writer5);
          out = _jsp_writer5;
            _jsp_tag0.doCatch(t);
          } finally {
            _jsp_tag0.doFinally();
          }
          pageContext.write(_jsp_string4, 0, _jsp_string4.length);
          _caucho_expr_0.print(pageContext.getWriteStream(), pageContext, true);
          pageContext.write(_jsp_string5, 0, _jsp_string5.length);
          _caucho_expr_1.print(pageContext.getWriteStream(), pageContext, true);
          pageContext.write(_jsp_string6, 0, _jsp_string6.length);
          if (_caucho_expr_2.evalBoolean(pageContext)) {
            pageContext.write(_jsp_string7, 0, _jsp_string7.length);
          }
          pageContext.write(_jsp_string8, 0, _jsp_string8.length);
          if (_jsp_tag3 == null) {
            _jsp_tag3 = new org.apache.taglibs.standard.tag.el.core.ForEachTag();
            _jsp_tag3.setPageContext(pageContext);
            _jsp_tag3.setParent((javax.servlet.jsp.tagext.Tag) null);
            _jsp_tag3.setVarStatus("status");
            _jsp_tag3.setVar("attribute");
          }

          _jsp_tag3.setItems("${typeListBean.hashMap['brand']}");
          javax.servlet.jsp.JspWriter _jsp_writer9 = out;
          try {
            int _jspEval10 = _jsp_tag3.doStartTag();
            if (_jspEval10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
              do {
                pageContext.write(_jsp_string9, 0, _jsp_string9.length);
                _caucho_expr_3.print(pageContext.getWriteStream(), pageContext, true);
                pageContext.write(_jsp_string10, 0, _jsp_string10.length);
                if (_caucho_expr_4.evalBoolean(pageContext)) {
                  pageContext.write(_jsp_string7, 0, _jsp_string7.length);
                }
                pageContext.write(_jsp_string11, 0, _jsp_string11.length);
                _caucho_expr_5.print(pageContext.getWriteStream(), pageContext, true);
                pageContext.write(_jsp_string12, 0, _jsp_string12.length);
              } while (_jsp_tag3.doAfterBody() == javax.servlet.jsp.tagext.IterationTag.EVAL_BODY_AGAIN);
            }
            } catch (Throwable t) {
            pageContext.setWriter(_jsp_writer9);
            out = _jsp_writer9;
              _jsp_tag3.doCatch(t);
            } finally {
              _jsp_tag3.doFinally();
            }
            pageContext.write(_jsp_string13, 0, _jsp_string13.length);
            if (_caucho_expr_6.evalBoolean(pageContext)) {
              pageContext.write(_jsp_string7, 0, _jsp_string7.length);
            }
            pageContext.write(_jsp_string14, 0, _jsp_string14.length);
            _jsp_tag3.setItems("${typeListBean.hashMap['catalogue_category']}");
            javax.servlet.jsp.JspWriter _jsp_writer12 = out;
            try {
              int _jspEval13 = _jsp_tag3.doStartTag();
              if (_jspEval13 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  pageContext.write(_jsp_string9, 0, _jsp_string9.length);
                  _caucho_expr_3.print(pageContext.getWriteStream(), pageContext, true);
                  pageContext.write(_jsp_string10, 0, _jsp_string10.length);
                  if (_caucho_expr_7.evalBoolean(pageContext)) {
                    pageContext.write(_jsp_string7, 0, _jsp_string7.length);
                  }
                  pageContext.write(_jsp_string11, 0, _jsp_string11.length);
                  _caucho_expr_5.print(pageContext.getWriteStream(), pageContext, true);
                  pageContext.write(_jsp_string12, 0, _jsp_string12.length);
                } while (_jsp_tag3.doAfterBody() == javax.servlet.jsp.tagext.IterationTag.EVAL_BODY_AGAIN);
              }
              } catch (Throwable t) {
              pageContext.setWriter(_jsp_writer12);
              out = _jsp_writer12;
                _jsp_tag3.doCatch(t);
              } finally {
                _jsp_tag3.doFinally();
              }
              pageContext.write(_jsp_string15, 0, _jsp_string15.length);
              if (_caucho_expr_8.evalBoolean(pageContext)) {
                pageContext.write(_jsp_string16, 0, _jsp_string16.length);
              }
              else {
                pageContext.write(_jsp_string17, 0, _jsp_string17.length);
                if (_jsp_tag9 == null) {
                  _jsp_tag9 = new org.apache.taglibs.standard.tag.el.core.ForEachTag();
                  _jsp_tag9.setPageContext(pageContext);
                  _jsp_tag9.setParent((javax.servlet.jsp.tagext.Tag) null);
                  _jsp_tag9.setVarStatus("status");
                  _jsp_tag9.setItems("${catalogueItemListBean.list}");
                  _jsp_tag9.setVar("catalogueItem");
                }

                javax.servlet.jsp.JspWriter _jsp_writer15 = out;
                try {
                  int _jspEval16 = _jsp_tag9.doStartTag();
                  if (_jspEval16 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                    do {
                      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
                      _caucho_expr_9.print(pageContext.getWriteStream(), pageContext, true);
                      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
                      if (_caucho_expr_10.evalBoolean(pageContext)) {
                        pageContext.write(_jsp_string20, 0, _jsp_string20.length);
                      }
                      pageContext.write(_jsp_string21, 0, _jsp_string21.length);
                      if (_caucho_expr_11.evalBoolean(pageContext)) {
                        pageContext.write(_jsp_string22, 0, _jsp_string22.length);
                      }
                      pageContext.write(_jsp_string23, 0, _jsp_string23.length);
                      _caucho_expr_12.print(pageContext.getWriteStream(), pageContext, true);
                      pageContext.write(_jsp_string24, 0, _jsp_string24.length);
                      _caucho_expr_13.print(pageContext.getWriteStream(), pageContext, true);
                      pageContext.write(_jsp_string25, 0, _jsp_string25.length);
                      if (_caucho_expr_14.print(pageContext.getWriteStream(), pageContext, true)) {
                        com.caucho.el.Expr.toStreamEscaped(pageContext.getWriteStream(), "N/A");
                      }
                      pageContext.write(_jsp_string26, 0, _jsp_string26.length);
                      if (_jsp_tag13 == null) {
                        _jsp_tag13 = new org.apache.taglibs.standard.tag.el.core.ForEachTag();
                        _jsp_tag13.setPageContext(pageContext);
                        _jsp_tag13.setParent(_jsp_tag9);
                        _jsp_tag13.setVarStatus("status");
                        _jsp_tag13.setVar("attribute");
                      }

                      _jsp_tag13.setItems("${typeListBean.hashMap['brand']}");
                      javax.servlet.jsp.JspWriter _jsp_writer18 = out;
                      try {
                        int _jspEval19 = _jsp_tag13.doStartTag();
                        if (_jspEval19 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                          do {
                            pageContext.write(_jsp_string27, 0, _jsp_string27.length);
                            if (_caucho_expr_15.evalBoolean(pageContext)) {
                              _caucho_expr_5.print(pageContext.getWriteStream(), pageContext, true);
                            }
                            pageContext.write(_jsp_string28, 0, _jsp_string28.length);
                          } while (_jsp_tag13.doAfterBody() == javax.servlet.jsp.tagext.IterationTag.EVAL_BODY_AGAIN);
                        }
                        } catch (Throwable t) {
                        pageContext.setWriter(_jsp_writer18);
                        out = _jsp_writer18;
                          _jsp_tag13.doCatch(t);
                        } finally {
                          _jsp_tag13.doFinally();
                        }
                        pageContext.write(_jsp_string29, 0, _jsp_string29.length);
                        _jsp_tag13.setItems("${typeListBean.hashMap['catalogue_category']}");
                        javax.servlet.jsp.JspWriter _jsp_writer21 = out;
                        try {
                          int _jspEval22 = _jsp_tag13.doStartTag();
                          if (_jspEval22 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            do {
                              pageContext.write(_jsp_string27, 0, _jsp_string27.length);
                              if (_caucho_expr_16.evalBoolean(pageContext)) {
                                _caucho_expr_5.print(pageContext.getWriteStream(), pageContext, true);
                              }
                              pageContext.write(_jsp_string28, 0, _jsp_string28.length);
                            } while (_jsp_tag13.doAfterBody() == javax.servlet.jsp.tagext.IterationTag.EVAL_BODY_AGAIN);
                          }
                          } catch (Throwable t) {
                          pageContext.setWriter(_jsp_writer21);
                          out = _jsp_writer21;
                            _jsp_tag13.doCatch(t);
                          } finally {
                            _jsp_tag13.doFinally();
                          }
                          pageContext.write(_jsp_string29, 0, _jsp_string29.length);
                          _jsp_tag13.setItems("${typeListBean.hashMap['catalogue_type']}");
                          javax.servlet.jsp.JspWriter _jsp_writer24 = out;
                          try {
                            int _jspEval25 = _jsp_tag13.doStartTag();
                            if (_jspEval25 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                              do {
                                pageContext.write(_jsp_string27, 0, _jsp_string27.length);
                                if (_caucho_expr_17.evalBoolean(pageContext)) {
                                  _caucho_expr_5.print(pageContext.getWriteStream(), pageContext, true);
                                }
                                pageContext.write(_jsp_string28, 0, _jsp_string28.length);
                              } while (_jsp_tag13.doAfterBody() == javax.servlet.jsp.tagext.IterationTag.EVAL_BODY_AGAIN);
                            }
                            } catch (Throwable t) {
                            pageContext.setWriter(_jsp_writer24);
                            out = _jsp_writer24;
                              _jsp_tag13.doCatch(t);
                            } finally {
                              _jsp_tag13.doFinally();
                            }
                            pageContext.write(_jsp_string30, 0, _jsp_string30.length);
                            _caucho_expr_12.print(pageContext.getWriteStream(), pageContext, true);
                            pageContext.write(_jsp_string31, 0, _jsp_string31.length);
                            _caucho_expr_12.print(pageContext.getWriteStream(), pageContext, true);
                            pageContext.write(_jsp_string32, 0, _jsp_string32.length);
                          } while (_jsp_tag9.doAfterBody() == javax.servlet.jsp.tagext.IterationTag.EVAL_BODY_AGAIN);
                        }
                        } catch (Throwable t) {
                        pageContext.setWriter(_jsp_writer15);
                        out = _jsp_writer15;
                          _jsp_tag9.doCatch(t);
                        } finally {
                          _jsp_tag9.doFinally();
                        }
                        pageContext.write(_jsp_string33, 0, _jsp_string33.length);
                      }
                      pageContext.write(_jsp_string34, 0, _jsp_string34.length);
                      com.caucho.jsp.QBodyContent _jsp_endTagHack26 = null;
                      _jsp_tag0.setUrl("/include/jsp/multipage.jsp");
                      javax.servlet.jsp.JspWriter _jsp_writer27 = out;
                      try {
                        int _jspEval28 = _jsp_tag0.doStartTag();
                        if (_jspEval28 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                          if (_jspEval28 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED) {
                            out = pageContext.pushBody();
                            _jsp_endTagHack26 = (com.caucho.jsp.QBodyContent) out;
                            _jsp_tag0.setBodyContent(_jsp_endTagHack26);
                          }
                          pageContext.write(_jsp_string35, 0, _jsp_string35.length);
                          if (_jsp_tag16 == null) {
                            _jsp_tag16 = new org.apache.taglibs.standard.tag.el.core.ParamTag();
                            _jsp_tag16.setPageContext(pageContext);
                            _jsp_tag16.setParent(_jsp_tag0);
                          }

                          _jsp_tag16.setName("domain");
                          _jsp_tag16.setValue("catalogueItem");
                          _jsp_tag16.doStartTag();
                          _jsp_tag16.setBodyContent(null);
                          int _jsp_endTagVar32 = _jsp_tag16.doEndTag();
                          if (_jsp_endTagVar32 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
                            return;
                          pageContext.write(_jsp_string35, 0, _jsp_string35.length);
                          _jsp_tag16.setName("listBean");
                          _jsp_tag16.setValue("catalogueItemListBean");
                          _jsp_tag16.doStartTag();
                          _jsp_tag16.setBodyContent(null);
                          int _jsp_endTagVar36 = _jsp_tag16.doEndTag();
                          if (_jsp_endTagVar36 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
                            return;
                          pageContext.write(_jsp_string36, 0, _jsp_string36.length);
                          if (_jspEval28 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED) {
                            out = pageContext.popBody();
                          } else {
                            _jsp_tag0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) null);
                          }
                        }
                        int _jsp_endTagVar37 = _jsp_tag0.doEndTag();
                        if (_jsp_endTagHack26 != null) {
                          pageContext.releaseBody(_jsp_endTagHack26);
                          _jsp_endTagHack26 = null;
                        }
                        if (_jsp_endTagVar37 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
                          return;
                        } catch (Throwable t) {
                        pageContext.setWriter(_jsp_writer27);
                        out = _jsp_writer27;
                          _jsp_tag0.doCatch(t);
                        } finally {
                          _jsp_tag0.doFinally();
                        }
                        pageContext.write(_jsp_string37, 0, _jsp_string37.length);
                      } catch (java.lang.Throwable _jsp_e) {
                        pageContext.handlePageException(_jsp_e);
                      } finally {
                        if (_jsp_tag0 != null)
                          _jsp_tag0.release();
                        if (_jsp_tag1 != null)
                          _jsp_tag1.release();
                        if (_jsp_tag2 != null)
                          _jsp_tag2.release();
                        if (_jsp_tag3 != null)
                          _jsp_tag3.release();
                        if (_jsp_tag4 != null)
                          _jsp_tag4.release();
                        if (_jsp_tag5 != null)
                          _jsp_tag5.release();
                        if (_jsp_tag6 != null)
                          _jsp_tag6.release();
                        if (_jsp_tag7 != null)
                          _jsp_tag7.release();
                        if (_jsp_tag8 != null)
                          _jsp_tag8.release();
                        if (_jsp_tag9 != null)
                          _jsp_tag9.release();
                        if (_jsp_tag10 != null)
                          _jsp_tag10.release();
                        if (_jsp_tag11 != null)
                          _jsp_tag11.release();
                        if (_jsp_tag12 != null)
                          _jsp_tag12.release();
                        if (_jsp_tag13 != null)
                          _jsp_tag13.release();
                        if (_jsp_tag14 != null)
                          _jsp_tag14.release();
                        if (_jsp_tag15 != null)
                          _jsp_tag15.release();
                        if (_jsp_tag16 != null)
                          _jsp_tag16.release();
                        JspFactory.getDefaultFactory().releasePageContext(pageContext);
                      }
                    }

                    private com.caucho.java.LineMap _caucho_line_map;
                    private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

                    public boolean _caucho_isModified()
                    {
                      if (_caucho_isDead)
                        return true;
                      if (com.caucho.util.CauchoSystem.getVersionId() != -2089842223)
                        return true;
                      for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
                        com.caucho.vfs.Depend depend;
                        depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
                        if (depend.isModified())
                          return true;
                      }
                      return false;
                    }

                    public long _caucho_lastModified()
                    {
                      return 0;
                    }

                    public com.caucho.java.LineMap _caucho_getLineMap()
                    {
                      return _caucho_line_map;
                    }

                    public void destroy()
                    {
                        _caucho_isDead = true;
                        super.destroy();
                    }

                    public void init(com.caucho.java.LineMap lineMap,
                                     com.caucho.vfs.Path appDir)
                      throws javax.servlet.ServletException
                    {
                      com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
                      com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
                      mergePath.addMergePath(appDir);
                      mergePath.addMergePath(resinHome);
                      mergePath.addClassPath(getClass().getClassLoader());
                      _caucho_line_map = new com.caucho.java.LineMap("_catalogueItemList__jsp.java", "/material/catalogueItemList.jsp");
                      _caucho_line_map.add(1, 1);
                      _caucho_line_map.add(1, 43);
                      _caucho_line_map.add(3, 44);
                      _caucho_line_map.add(5, 45);
                      _caucho_line_map.add(6, 54);
                      _caucho_line_map.add(7, 62);
                      _caucho_line_map.add(8, 71);
                      _caucho_line_map.add(22, 80);
                      _caucho_line_map.add(22, 91);
                      _caucho_line_map.add(29, 102);
                      _caucho_line_map.add(29, 107);
                      _caucho_line_map.add(43, 118);
                      _caucho_line_map.add(44, 120);
                      _caucho_line_map.add(47, 122);
                      _caucho_line_map.add(48, 126);
                      _caucho_line_map.add(48, 140);
                      _caucho_line_map.add(49, 143);
                      _caucho_line_map.add(49, 147);
                      _caucho_line_map.add(55, 159);
                      _caucho_line_map.add(56, 163);
                      _caucho_line_map.add(56, 169);
                      _caucho_line_map.add(57, 172);
                      _caucho_line_map.add(57, 176);
                      _caucho_line_map.add(82, 188);
                      _caucho_line_map.add(89, 193);
                      _caucho_line_map.add(89, 207);
                      _caucho_line_map.add(91, 210);
                      _caucho_line_map.add(94, 214);
                      _caucho_line_map.add(97, 218);
                      _caucho_line_map.add(98, 220);
                      _caucho_line_map.add(99, 222);
                      _caucho_line_map.add(101, 226);
                      _caucho_line_map.add(101, 240);
                      _caucho_line_map.add(102, 242);
                      _caucho_line_map.add(106, 255);
                      _caucho_line_map.add(106, 261);
                      _caucho_line_map.add(107, 263);
                      _caucho_line_map.add(111, 276);
                      _caucho_line_map.add(111, 282);
                      _caucho_line_map.add(112, 284);
                      _caucho_line_map.add(116, 297);
                      _caucho_line_map.add(128, 313);
                      _caucho_line_map.add(128, 324);
                      _caucho_line_map.add(129, 335);
                      _caucho_line_map.add(130, 339);
                      _caucho_line_map.add(130, 343);
                      com.caucho.vfs.Depend depend;
                      depend = new com.caucho.vfs.Depend(appDir.lookup("material/catalogueItemList.jsp"), 1087946792000L, 6438L);
                      _caucho_depends.add(depend);
                    }

                    protected void _caucho_clearDepends()
                    {
                      _caucho_depends.clear();
                    }
                    private static com.caucho.el.Expr _caucho_expr_0 =
                      new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("catalogueItemListForm"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("reference"));
                    private static com.caucho.el.Expr _caucho_expr_1 =
                      new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("catalogueItemListForm"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("designation"));
                    private static com.caucho.el.Expr _caucho_expr_2 =
                      new com.caucho.el.EqExpr(6, new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("catalogueItemListBean"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("brandId")), new com.caucho.el.UnaryExpr(15, new com.caucho.el.LongLiteral(1L)));
                    private static com.caucho.el.Expr _caucho_expr_3 =
                      new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("attribute"), new com.caucho.el.StringLiteral("key"));
                    private static com.caucho.el.Expr _caucho_expr_4 =
                      new com.caucho.el.EqExpr(6, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("attribute"), new com.caucho.el.StringLiteral("key")), new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("catalogueItemListForm"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("brandId")));
                    private static com.caucho.el.Expr _caucho_expr_5 =
                      new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("attribute"), new com.caucho.el.StringLiteral("value"));
                    private static com.caucho.el.Expr _caucho_expr_6 =
                      new com.caucho.el.EqExpr(6, new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("catalogueItemListBean"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("categoryId")), new com.caucho.el.UnaryExpr(15, new com.caucho.el.LongLiteral(1L)));
                    private static com.caucho.el.Expr _caucho_expr_7 =
                      new com.caucho.el.EqExpr(6, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("attribute"), new com.caucho.el.StringLiteral("key")), new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("catalogueItemListForm"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("categoryId")));
                    private static com.caucho.el.Expr _caucho_expr_8 =
                      new com.caucho.el.UnaryExpr(16, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("catalogueItemListBean"), new com.caucho.el.StringLiteral("list")));
                    private static com.caucho.el.Expr _caucho_expr_9 =
                      new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("catalogue"), new com.caucho.el.StringLiteral("id"));
                    private static com.caucho.el.Expr _caucho_expr_10 =
                      new com.caucho.el.EqExpr(6, new com.caucho.el.BinaryExpr(5, new com.caucho.el.BinaryExpr(1, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("status"), new com.caucho.el.StringLiteral("index")), new com.caucho.el.LongLiteral(1L)), new com.caucho.el.LongLiteral(2L)), new com.caucho.el.LongLiteral(0L));
                    private static com.caucho.el.Expr _caucho_expr_11 =
                      new com.caucho.el.EqExpr(7, new com.caucho.el.BinaryExpr(5, new com.caucho.el.BinaryExpr(1, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("status"), new com.caucho.el.StringLiteral("index")), new com.caucho.el.LongLiteral(1L)), new com.caucho.el.LongLiteral(2L)), new com.caucho.el.LongLiteral(0L));
                    private static com.caucho.el.Expr _caucho_expr_12 =
                      new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("catalogueItem"), new com.caucho.el.StringLiteral("id"));
                    private static com.caucho.el.Expr _caucho_expr_13 =
                      new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("catalogueItem"), new com.caucho.el.StringLiteral("reference"));
                    private static com.caucho.el.Expr _caucho_expr_14 =
                      new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("catalogueItem"), new com.caucho.el.StringLiteral("designation"));
                    private static com.caucho.el.Expr _caucho_expr_15 =
                      new com.caucho.el.EqExpr(6, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("attribute"), new com.caucho.el.StringLiteral("key")), new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("catalogueItem"), new com.caucho.el.StringLiteral("brandId")));
                    private static com.caucho.el.Expr _caucho_expr_16 =
                      new com.caucho.el.EqExpr(6, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("attribute"), new com.caucho.el.StringLiteral("key")), new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("catalogueItem"), new com.caucho.el.StringLiteral("categoryId")));
                    private static com.caucho.el.Expr _caucho_expr_17 =
                      new com.caucho.el.EqExpr(6, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("attribute"), new com.caucho.el.StringLiteral("key")), new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("catalogueItem"), new com.caucho.el.StringLiteral("typeId")));

                    private static byte []_jsp_string1;
                    private static byte []_jsp_string32;
                    private static byte []_jsp_string34;
                    private static byte []_jsp_string12;
                    private static byte []_jsp_string2;
                    private static byte []_jsp_string13;
                    private static byte []_jsp_string7;
                    private static byte []_jsp_string37;
                    private static byte []_jsp_string26;
                    private static byte []_jsp_string35;
                    private static byte []_jsp_string8;
                    private static byte []_jsp_string36;
                    private static byte []_jsp_string31;
                    private static byte []_jsp_string14;
                    private static byte []_jsp_string22;
                    private static byte []_jsp_string23;
                    private static byte []_jsp_string10;
                    private static byte []_jsp_string30;
                    private static byte []_jsp_string0;
                    private static byte []_jsp_string11;
                    private static byte []_jsp_string33;
                    private static byte []_jsp_string20;
                    private static byte []_jsp_string17;
                    private static byte []_jsp_string25;
                    private static byte []_jsp_string6;
                    private static byte []_jsp_string3;
                    private static byte []_jsp_string5;
                    private static byte []_jsp_string15;
                    private static byte []_jsp_string18;
                    private static byte []_jsp_string29;
                    private static byte []_jsp_string27;
                    private static byte []_jsp_string9;
                    private static byte []_jsp_string28;
                    private static byte []_jsp_string4;
                    private static byte []_jsp_string24;
                    private static byte []_jsp_string16;
                    private static byte []_jsp_string19;
                    private static byte []_jsp_string21;
                    static {
                      _jsp_string1 = "\n".getBytes();
                      _jsp_string32 = "'; document.listForm.action.value='delete'; document.listForm.subAction.value='one'; document.listForm.submit();\"/>\n					</td>\n				</tr>\n				".getBytes();
                      _jsp_string34 = "\n			</table>\n		</div>\n		\n		<!-- multipage navigation -->\n		".getBytes();
                      _jsp_string12 = "</option>\n					".getBytes();
                      _jsp_string2 = "\n\n<?xml version=\"1\" encoding=\"ISO-8859-1\"?>\n<!DOCTYPE html PUBLIC \"- //w3c//DTD XHTML 1.0 Strict//EN\" \n\"http://www.w3.org/TR/xhtml11/DTD/xhtml11-strict.dtd\">\n\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n	<head>\n		<title>Liste catalogue r\u00e9f\u00e9rences</title>\n		<link href=\"/include/style/styleList.css\" rel=\"stylesheet\" type=\"text/css\">\n		<link href=\"/include/style/global.css\" rel=\"stylesheet\" type=\"text/css\">\n		<link href=\"/include/style/header.css\" rel=\"stylesheet\" type=\"text/css\">\n		\n		<!-- create dynamic menu -->\n		".getBytes();
                      _jsp_string13 = "\n				</select>\n			</p>\n			<p class=\"boxSearch\">Cat\u00e9gorie:&nbsp;\n				<select name=\"categoryId\">\n					<option value=\"-1\" ".getBytes();
                      _jsp_string7 = "SELECTED".getBytes();
                      _jsp_string37 = "\n		\n		</form>\n	<body>\n	\n</html>".getBytes();
                      _jsp_string26 = "</td>\n					<td>\n						".getBytes();
                      _jsp_string35 = "\n			".getBytes();
                      _jsp_string8 = ">Toutes les marques</option>\n					".getBytes();
                      _jsp_string36 = "\n		".getBytes();
                      _jsp_string31 = "'; document.listForm.action.value='update'; document.listForm.subAction.value='init'; document.listForm.submit();\"/>&nbsp;&nbsp;\n						<img src=\"/include/pictures/glass.png\" alt=\"Voir d\u00e9tail\">&nbsp;&nbsp;\n						<img src=\"/include/pictures/trash.png\" alt=\"Supprimer\" onclick=\"document.listForm.id.value='".getBytes();
                      _jsp_string14 = ">Toutes les cat\u00e9gories</option>\n					".getBytes();
                      _jsp_string22 = "\n				<tr class=\"result_odd\">\n					".getBytes();
                      _jsp_string23 = "\n					<td><input type=\"checkbox\" value=\"".getBytes();
                      _jsp_string10 = "\" ".getBytes();
                      _jsp_string30 = "\n					</td>\n					<td>&nbsp;\n						<img src=\"/include/pictures/pencil.png\" alt=\"Modifier\" onclick=\"document.listForm.id.value='".getBytes();
                      _jsp_string0 = "\n\n".getBytes();
                      _jsp_string11 = ">".getBytes();
                      _jsp_string33 = "\n	".getBytes();
                      _jsp_string20 = " \n				<tr class=\"result_par\">\n					".getBytes();
                      _jsp_string17 = "\n				".getBytes();
                      _jsp_string25 = "</td>\n					<td>".getBytes();
                      _jsp_string6 = "\"></p>\n			<p class=\"boxSearch\">Marque:&nbsp;\n				<select name=\"brandId\">\n					<option value=\"-1\" ".getBytes();
                      _jsp_string3 = "\n	\n	</head>\n	\n	<body>\n	\n		<!-- display header : company logo + menu + user info -->\n		".getBytes();
                      _jsp_string5 = "\"></p>\n			<p class=\"boxSearch\">D\u00e9signation:&nbsp;<input type=\"text\" name=\"designation\" length=\"30\" value=\"".getBytes();
                      _jsp_string15 = "\n				</select>\n			</p>\n		</div>\n		\n		\n		<div class=\"boxTitle\">&nbsp;&nbsp;Actions:</div>\n		<div class=\"boxCol\">\n			<p class=\"boxAction\"><a class=\"classicButtonBlue\" onclick=\"document.listForm.action.value='list'; document.listForm.subAction.value='init'; document.listForm.submit();\">&nbsp;[ rechercher ]&nbsp;</a></p>\n			<p class=\"boxAction\"><a class=\"classicButtonBlue\" onclick=\"document.listForm.action.value='add'; document.listForm.subAction.value='init'; document.listForm.submit();\">&nbsp;[ ajouter ]&nbsp;</a></p>\n			<p class=\"boxAction\"><a class=\"classicButtonBlue\" onclick=\"\">&nbsp;[ supprimer ]&nbsp;</a></p>\n		</div>\n		\n		<div class=\"boxResults\">\n			<table border=\"0\" width=\"100%\" cellpadding=\"0px\" cellspacing=\"0px\"> \n				<tr>\n					<th width=\"2%\">&nbsp;</th>\n					<th width=\"13%\">R\u00e9f\u00e9rence</th>\n					<th width=\"32%\">D\u00e9signation</th>\n					<th width=\"17%\">Marque</th>\n					<th width=\"20%\">Cat\u00e9gorie</th>\n					<th width=\"8%\">Type</th>\n					<th width=\"8%\">Actions</th>\n				</tr>\n".getBytes();
                      _jsp_string18 = "\n				<!-- catalogue id ".getBytes();
                      _jsp_string29 = "\n					</td>\n					<td>\n						".getBytes();
                      _jsp_string27 = "\n							".getBytes();
                      _jsp_string9 = "\n					<option value=\"".getBytes();
                      _jsp_string28 = "\n						".getBytes();
                      _jsp_string4 = "\n	\n		<form name=\"listForm\" action=\"DomainActionServlet\" method=\"POST\">\n			<input type=\"hidden\" name=\"domain\" value=\"catalogueItem\">\n			<input type=\"hidden\" name=\"action\">\n			<input type=\"hidden\" name=\"subAction\">\n			<input type=\"hidden\" name=\"id\">\n	\n		<br>\n				\n		<h1 class=\"title\">Catalogue R\u00e9f\u00e9rences&nbsp;&nbsp;:&nbsp;:&nbsp;&nbsp;Liste</h1>\n		\n		<div class=\"boxTitle\">&nbsp;&nbsp;Recherche par: </div>\n		<div class=\"boxCol\">\n			<p class=\"boxSearch\">R\u00e9f\u00e9rence:&nbsp;<input type=\"text\" name=\"reference\" length=\"30\" value=\"".getBytes();
                      _jsp_string24 = "\"></td>\n					<td>".getBytes();
                      _jsp_string16 = "\n				<tr class=\"noresult\">\n					<td colspan=\"7\">Aucun r\u00e9sultat</td>\n				</tr>\n	".getBytes();
                      _jsp_string19 = " -->\n					".getBytes();
                      _jsp_string21 = "\n					".getBytes();
                    }
                  }
