/*
 * JSP generated by Resin 2.1.12 (built Tue Dec  9 14:58:25 PST 2003)
 */

import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _global__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=iso-8859-1");
    org.apache.taglibs.standard.tag.el.core.ImportTag _jsp_tag0 = null;
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      com.eurocash.data.administration.employee.EmployeeBean employeeBean;
      synchronized (session) {
        employeeBean = (com.eurocash.data.administration.employee.EmployeeBean) session.getAttribute("employeeBean");
        if (employeeBean == null) {
          employeeBean = new com.eurocash.data.administration.employee.EmployeeBean();
          session.setAttribute("employeeBean", employeeBean);
        }
      }
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      com.eurocash.data.administration.agency.AgenciesBean agenciesBean;
      synchronized (application) {
        agenciesBean = (com.eurocash.data.administration.agency.AgenciesBean) application.getAttribute("agenciesBean");
        if (agenciesBean == null) {
          agenciesBean = new com.eurocash.data.administration.agency.AgenciesBean();
          application.setAttribute("agenciesBean", agenciesBean);
        }
      }
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      if (_jsp_tag0 == null) {
        _jsp_tag0 = new org.apache.taglibs.standard.tag.el.core.ImportTag();
        _jsp_tag0.setPageContext(pageContext);
        _jsp_tag0.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag0.setUrl("/include/jsp/menu.jsp");
      javax.servlet.jsp.JspWriter _jsp_writer1 = out;
      try {
        _jsp_tag0.doStartTag();
        _jsp_tag0.setBodyContent(null);
        int _jsp_endTagVar3 = _jsp_tag0.doEndTag();
        if (_jsp_endTagVar3 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
          return;
        } catch (Throwable t) {
        pageContext.setWriter(_jsp_writer1);
        out = _jsp_writer1;
          _jsp_tag0.doCatch(t);
        } finally {
          _jsp_tag0.doFinally();
        }
        pageContext.write(_jsp_string3, 0, _jsp_string3.length);
        _jsp_tag0.setUrl("/include/jsp/header.jsp");
        javax.servlet.jsp.JspWriter _jsp_writer5 = out;
        try {
          _jsp_tag0.doStartTag();
          _jsp_tag0.setBodyContent(null);
          int _jsp_endTagVar7 = _jsp_tag0.doEndTag();
          if (_jsp_endTagVar7 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
            return;
          } catch (Throwable t) {
          pageContext.setWriter(_jsp_writer5);
          out = _jsp_writer5;
            _jsp_tag0.doCatch(t);
          } finally {
            _jsp_tag0.doFinally();
          }
          pageContext.write(_jsp_string4, 0, _jsp_string4.length);
        } catch (java.lang.Throwable _jsp_e) {
          pageContext.handlePageException(_jsp_e);
        } finally {
          if (_jsp_tag0 != null)
            _jsp_tag0.release();
          JspFactory.getDefaultFactory().releasePageContext(pageContext);
        }
      }

      private com.caucho.java.LineMap _caucho_line_map;
      private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

      public boolean _caucho_isModified()
      {
        if (_caucho_isDead)
          return true;
        if (com.caucho.util.CauchoSystem.getVersionId() != -2089842223)
          return true;
        for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
          com.caucho.vfs.Depend depend;
          depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
          if (depend.isModified())
            return true;
        }
        return false;
      }

      public long _caucho_lastModified()
      {
        return 0;
      }

      public com.caucho.java.LineMap _caucho_getLineMap()
      {
        return _caucho_line_map;
      }

      public void destroy()
      {
          _caucho_isDead = true;
          super.destroy();
      }

      public void init(com.caucho.java.LineMap lineMap,
                       com.caucho.vfs.Path appDir)
        throws javax.servlet.ServletException
      {
        com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
        com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
        mergePath.addMergePath(appDir);
        mergePath.addMergePath(resinHome);
        mergePath.addClassPath(getClass().getClassLoader());
        _caucho_line_map = new com.caucho.java.LineMap("_global__jsp.java", "/global.jsp");
        _caucho_line_map.add(1, 1);
        _caucho_line_map.add(1, 26);
        _caucho_line_map.add(3, 27);
        _caucho_line_map.add(5, 28);
        _caucho_line_map.add(6, 37);
        _caucho_line_map.add(21, 46);
        _caucho_line_map.add(21, 57);
        _caucho_line_map.add(28, 68);
        _caucho_line_map.add(28, 73);
        com.caucho.vfs.Depend depend;
        depend = new com.caucho.vfs.Depend(appDir.lookup("global.jsp"), 1086218289000L, 1193L);
        _caucho_depends.add(depend);
      }

      protected void _caucho_clearDepends()
      {
        _caucho_depends.clear();
      }

      private static byte []_jsp_string0;
      private static byte []_jsp_string3;
      private static byte []_jsp_string1;
      private static byte []_jsp_string2;
      private static byte []_jsp_string4;
      static {
        _jsp_string0 = "\n\n".getBytes();
        _jsp_string3 = "\n	\n	</head>\n	\n	<body>\n	\n		<!-- display header : company logo + menu + user info -->\n		".getBytes();
        _jsp_string1 = "\n".getBytes();
        _jsp_string2 = "\n\n\n<?xml version=\"1\" encoding=\"ISO-8859-1\"?>\n<!DOCTYPE html PUBLIC \"- //w3c//DTD XHTML 1.0 Strict//EN\" \n\"http://www.w3.org/TR/xhtml11/DTD/xhtml11-strict.dtd\">\n\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n	<head>\n		<title>Accueil</title>\n		<link href=\"/include/style/styleList.css\" rel=\"stylesheet\" type=\"text/css\">\n		<link href=\"/include/style/global.css\" rel=\"stylesheet\" type=\"text/css\">\n		<link href=\"/include/style/header.css\" rel=\"stylesheet\" type=\"text/css\">\n		\n		<!-- create dynamic menu -->\n		".getBytes();
        _jsp_string4 = "\n\n		<br>\n				\n		<h1 class=\"title\">Accueil</h1>\n\n		<br><br><br>\n\n		<div class=\"message\">BIENVENUE DANS L'APPLICATION eGestion Commerciale (version 0.1)</<div>\n	</body>\n</html>".getBytes();
      }
    }
