/*
 * JSP generated by Resin 2.1.12 (built Tue Dec  9 14:58:25 PST 2003)
 */

import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _login__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html");
    try {
      com.eurocash.common.ErrorBean errorBean;
      errorBean = (com.eurocash.common.ErrorBean) request.getAttribute("errorBean");
      if (errorBean == null) {
        errorBean = new com.eurocash.common.ErrorBean();
        request.setAttribute("errorBean", errorBean);
      }
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
       if (errorBean.isError()) { 
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((errorBean.getCode()));
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
       } 
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -2089842223)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_login__jsp.java", "/login.jsp");
    _caucho_line_map.add(1, 1);
    _caucho_line_map.add(1, 25);
    _caucho_line_map.add(31, 32);
    _caucho_line_map.add(32, 34);
    _caucho_line_map.add(33, 36);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("login.jsp"), 1088631392000L, 1937L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }

  private static byte []_jsp_string1;
  private static byte []_jsp_string2;
  private static byte []_jsp_string0;
  private static byte []_jsp_string3;
  static {
    _jsp_string1 = "\n  		<tr><td colspan=\"2\" class='login_failed' align=\"center\">".getBytes();
    _jsp_string2 = "</td></tr>	\n  		".getBytes();
    _jsp_string0 = "\n\n<html>\n\n<HEAD>\n  <TITLE>Papyrus - authentification</TITLE>\n\n  <link rel=\"StyleSheet\" HREF=\"/include/style/general.css\" type=\"text/css\">\n  <link rel=\"StyleSheet\" HREF=\"/include/style/global.css\" type=\"text/css\">\n\n</HEAD>\n\n<script language=\"JavaScript\">\n\n</script>\n\n<body>\n\n<form name=\"loginForm\" action=\"DomainActionServlet\" method=\"POST\">\n\n	<input type=\"hidden\" name=\"domain\" value=\"login\">\n	<br>\n	<br>\n	<table align=\"center\" border=\"0\" width=\"360px\" cellspacing=\"1\" cellpadding=\"1\" class=\"login_table\">\n  		<tr>\n  			<td align=\"left\" width=\"20%\"><img src=\"/include/pictures/login.png\"></td>\n    		<td align=\"center\" width=\"80%\" class=\"login_title\">:: Authentification ::</td>\n    	</tr>\n  		<tr><td height=\"20px\" colspan=\"2\">&nbsp;</td></tr>\n  		\n  		".getBytes();
    _jsp_string3 = "\n        \n        <tr><td colspan=\"2\">&nbsp;</td></tr>\n     	<tr><td align=\"center\" colspan=\"2\">\n       		<table border=\"0\">\n         		<tr height=\"30px\">\n           			<td width=\"70%\" class=\"login_text\">Login: </td>\n                    <td width=\"30%\"><input type=\"text\" name=\"login\" maxlength=\"10\" size=\"12\"></td>\n                </tr>\n         		<tr height=\"30px\">\n                	<td width=\"70%\" class=\"login_text\">Mot de passe: </td>\n               		<td width=\"30%\"><input type=\"password\" name=\"password\" maxlength=\"10\" size=\"12\"></td>\n         		</tr>\n        		<tr><td colspan=\"2\">&nbsp;</td></tr>\n         		<tr>\n           			<td colspan=\"2\" align=\"center\">\n	           			<a class=\"classicButtonGreen\" onclick=\"loginForm.submit();\">&nbsp;OK&nbsp;</a>\n           				<!-- <input type=\"submit\" value=\"OK\" class=\"button\"> -->\n           			</td>\n         		</tr>\n         	</table>\n         </td></tr>\n	</table>\n	\n</form>\n         		\n</body>\n\n</html>".getBytes();
  }
}
