/*
 * JSP generated by Resin 2.1.12 (built Tue Dec  9 14:58:25 PST 2003)
 */

package _administration;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _agencyList__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=iso-8859-1");
    org.apache.taglibs.standard.tag.el.core.ImportTag _jsp_tag0 = null;
    org.apache.taglibs.standard.tag.el.core.ParamTag _jsp_tag13 = null;
    org.apache.taglibs.standard.tag.el.core.OutTag _jsp_tag1 = null;
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jsp_tag2 = null;
    org.apache.taglibs.standard.tag.el.core.WhenTag _jsp_tag3 = null;
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jsp_tag4 = null;
    org.apache.taglibs.standard.tag.el.core.ForEachTag _jsp_tag5 = null;
    org.apache.taglibs.standard.tag.el.core.IfTag _jsp_tag6 = null;
    org.apache.taglibs.standard.tag.el.core.OutTag _jsp_tag7 = null;
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jsp_tag8 = null;
    org.apache.taglibs.standard.tag.el.core.WhenTag _jsp_tag9 = null;
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jsp_tag10 = null;
    org.apache.taglibs.standard.tag.el.core.OutTag _jsp_tag11 = null;
    org.apache.taglibs.standard.tag.el.core.OutTag _jsp_tag12 = null;
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      com.eurocash.data.ItemListBean agencyListBean;
      synchronized (session) {
        agencyListBean = (com.eurocash.data.ItemListBean) session.getAttribute("agencyListBean");
        if (agencyListBean == null) {
          agencyListBean = new com.eurocash.data.ItemListBean();
          session.setAttribute("agencyListBean", agencyListBean);
        }
      }
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      com.eurocash.data.mapping.form.FormMappingObject agencyListForm;
      synchronized (session) {
        agencyListForm = (com.eurocash.data.mapping.form.FormMappingObject) session.getAttribute("agencyListForm");
        if (agencyListForm == null) {
          throw new java.lang.InstantiationException("`com.eurocash.data.mapping.form.FormMappingObject' has no public zero-arg constructor");
        }
      }
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      com.eurocash.data.administration.employee.EmployeeBean employeeBean;
      synchronized (session) {
        employeeBean = (com.eurocash.data.administration.employee.EmployeeBean) session.getAttribute("employeeBean");
        if (employeeBean == null) {
          employeeBean = new com.eurocash.data.administration.employee.EmployeeBean();
          session.setAttribute("employeeBean", employeeBean);
        }
      }
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      com.eurocash.data.administration.agency.AgenciesBean agenciesBean;
      synchronized (application) {
        agenciesBean = (com.eurocash.data.administration.agency.AgenciesBean) application.getAttribute("agenciesBean");
        if (agenciesBean == null) {
          agenciesBean = new com.eurocash.data.administration.agency.AgenciesBean();
          application.setAttribute("agenciesBean", agenciesBean);
        }
      }
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      if (_jsp_tag0 == null) {
        _jsp_tag0 = new org.apache.taglibs.standard.tag.el.core.ImportTag();
        _jsp_tag0.setPageContext(pageContext);
        _jsp_tag0.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag0.setUrl("/include/jsp/menu.jsp");
      javax.servlet.jsp.JspWriter _jsp_writer1 = out;
      try {
        _jsp_tag0.doStartTag();
        _jsp_tag0.setBodyContent(null);
        int _jsp_endTagVar3 = _jsp_tag0.doEndTag();
        if (_jsp_endTagVar3 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
          return;
        } catch (Throwable t) {
        pageContext.setWriter(_jsp_writer1);
        out = _jsp_writer1;
          _jsp_tag0.doCatch(t);
        } finally {
          _jsp_tag0.doFinally();
        }
        pageContext.write(_jsp_string3, 0, _jsp_string3.length);
        _jsp_tag0.setUrl("/include/jsp/header.jsp");
        javax.servlet.jsp.JspWriter _jsp_writer5 = out;
        try {
          _jsp_tag0.doStartTag();
          _jsp_tag0.setBodyContent(null);
          int _jsp_endTagVar7 = _jsp_tag0.doEndTag();
          if (_jsp_endTagVar7 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
            return;
          } catch (Throwable t) {
          pageContext.setWriter(_jsp_writer5);
          out = _jsp_writer5;
            _jsp_tag0.doCatch(t);
          } finally {
            _jsp_tag0.doFinally();
          }
          pageContext.write(_jsp_string4, 0, _jsp_string4.length);
          _caucho_expr_0.print(pageContext.getWriteStream(), pageContext, true);
          pageContext.write(_jsp_string5, 0, _jsp_string5.length);
          if (_caucho_expr_1.evalBoolean(pageContext)) {
            pageContext.write(_jsp_string6, 0, _jsp_string6.length);
          }
          else {
            pageContext.write(_jsp_string7, 0, _jsp_string7.length);
            if (_jsp_tag5 == null) {
              _jsp_tag5 = new org.apache.taglibs.standard.tag.el.core.ForEachTag();
              _jsp_tag5.setPageContext(pageContext);
              _jsp_tag5.setParent((javax.servlet.jsp.tagext.Tag) null);
              _jsp_tag5.setVarStatus("status");
              _jsp_tag5.setItems("${agencyListBean.list}");
              _jsp_tag5.setVar("agency");
            }

            javax.servlet.jsp.JspWriter _jsp_writer9 = out;
            try {
              int _jspEval10 = _jsp_tag5.doStartTag();
              if (_jspEval10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  pageContext.write(_jsp_string8, 0, _jsp_string8.length);
                  if (_caucho_expr_2.evalBoolean(pageContext)) {
                    pageContext.write(_jsp_string9, 0, _jsp_string9.length);
                  }
                  pageContext.write(_jsp_string8, 0, _jsp_string8.length);
                  if (_caucho_expr_3.evalBoolean(pageContext)) {
                    pageContext.write(_jsp_string10, 0, _jsp_string10.length);
                  }
                  pageContext.write(_jsp_string11, 0, _jsp_string11.length);
                  _caucho_expr_4.print(pageContext.getWriteStream(), pageContext, true);
                  pageContext.write(_jsp_string12, 0, _jsp_string12.length);
                  _caucho_expr_5.print(pageContext.getWriteStream(), pageContext, true);
                  pageContext.write(_jsp_string13, 0, _jsp_string13.length);
                  if (_caucho_expr_6.evalBoolean(pageContext)) {
                    pageContext.write(_jsp_string14, 0, _jsp_string14.length);
                  }
                  else {
                    pageContext.write(_jsp_string15, 0, _jsp_string15.length);
                    _caucho_expr_7.print(pageContext.getWriteStream(), pageContext, true);
                    pageContext.write(_jsp_string15, 0, _jsp_string15.length);
                    _caucho_expr_8.print(pageContext.getWriteStream(), pageContext, true);
                    pageContext.write(_jsp_string15, 0, _jsp_string15.length);
                    _caucho_expr_9.print(pageContext.getWriteStream(), pageContext, true);
                    pageContext.write(_jsp_string16, 0, _jsp_string16.length);
                  }
                  pageContext.write(_jsp_string17, 0, _jsp_string17.length);
                  if (_caucho_expr_10.print(pageContext.getWriteStream(), pageContext, true)) {
                    com.caucho.el.Expr.toStreamEscaped(pageContext.getWriteStream(), "N/A");
                  }
                  pageContext.write(_jsp_string13, 0, _jsp_string13.length);
                  if (_caucho_expr_11.print(pageContext.getWriteStream(), pageContext, true)) {
                    com.caucho.el.Expr.toStreamEscaped(pageContext.getWriteStream(), "N/A");
                  }
                  pageContext.write(_jsp_string13, 0, _jsp_string13.length);
                  if (_caucho_expr_12.print(pageContext.getWriteStream(), pageContext, true)) {
                    com.caucho.el.Expr.toStreamEscaped(pageContext.getWriteStream(), "N/A");
                  }
                  pageContext.write(_jsp_string13, 0, _jsp_string13.length);
                  if (_caucho_expr_13.print(pageContext.getWriteStream(), pageContext, true)) {
                    com.caucho.el.Expr.toStreamEscaped(pageContext.getWriteStream(), "0");
                  }
                  pageContext.write(_jsp_string18, 0, _jsp_string18.length);
                  _caucho_expr_4.print(pageContext.getWriteStream(), pageContext, true);
                  pageContext.write(_jsp_string19, 0, _jsp_string19.length);
                  _caucho_expr_4.print(pageContext.getWriteStream(), pageContext, true);
                  pageContext.write(_jsp_string20, 0, _jsp_string20.length);
                } while (_jsp_tag5.doAfterBody() == javax.servlet.jsp.tagext.IterationTag.EVAL_BODY_AGAIN);
              }
              } catch (Throwable t) {
              pageContext.setWriter(_jsp_writer9);
              out = _jsp_writer9;
                _jsp_tag5.doCatch(t);
              } finally {
                _jsp_tag5.doFinally();
              }
              pageContext.write(_jsp_string21, 0, _jsp_string21.length);
            }
            pageContext.write(_jsp_string22, 0, _jsp_string22.length);
            com.caucho.jsp.QBodyContent _jsp_endTagHack11 = null;
            _jsp_tag0.setUrl("/include/jsp/multipage.jsp");
            javax.servlet.jsp.JspWriter _jsp_writer12 = out;
            try {
              int _jspEval13 = _jsp_tag0.doStartTag();
              if (_jspEval13 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                if (_jspEval13 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED) {
                  out = pageContext.pushBody();
                  _jsp_endTagHack11 = (com.caucho.jsp.QBodyContent) out;
                  _jsp_tag0.setBodyContent(_jsp_endTagHack11);
                }
                pageContext.write(_jsp_string8, 0, _jsp_string8.length);
                if (_jsp_tag13 == null) {
                  _jsp_tag13 = new org.apache.taglibs.standard.tag.el.core.ParamTag();
                  _jsp_tag13.setPageContext(pageContext);
                  _jsp_tag13.setParent(_jsp_tag0);
                }

                _jsp_tag13.setName("domain");
                _jsp_tag13.setValue("agency");
                _jsp_tag13.doStartTag();
                _jsp_tag13.setBodyContent(null);
                int _jsp_endTagVar17 = _jsp_tag13.doEndTag();
                if (_jsp_endTagVar17 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
                  return;
                pageContext.write(_jsp_string8, 0, _jsp_string8.length);
                _jsp_tag13.setName("listBean");
                _jsp_tag13.setValue("agencyListBean");
                _jsp_tag13.doStartTag();
                _jsp_tag13.setBodyContent(null);
                int _jsp_endTagVar21 = _jsp_tag13.doEndTag();
                if (_jsp_endTagVar21 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
                  return;
                pageContext.write(_jsp_string7, 0, _jsp_string7.length);
                if (_jspEval13 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED) {
                  out = pageContext.popBody();
                } else {
                  _jsp_tag0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) null);
                }
              }
              int _jsp_endTagVar22 = _jsp_tag0.doEndTag();
              if (_jsp_endTagHack11 != null) {
                pageContext.releaseBody(_jsp_endTagHack11);
                _jsp_endTagHack11 = null;
              }
              if (_jsp_endTagVar22 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
                return;
              } catch (Throwable t) {
              pageContext.setWriter(_jsp_writer12);
              out = _jsp_writer12;
                _jsp_tag0.doCatch(t);
              } finally {
                _jsp_tag0.doFinally();
              }
              pageContext.write(_jsp_string23, 0, _jsp_string23.length);
            } catch (java.lang.Throwable _jsp_e) {
              pageContext.handlePageException(_jsp_e);
            } finally {
              if (_jsp_tag0 != null)
                _jsp_tag0.release();
              if (_jsp_tag1 != null)
                _jsp_tag1.release();
              if (_jsp_tag2 != null)
                _jsp_tag2.release();
              if (_jsp_tag3 != null)
                _jsp_tag3.release();
              if (_jsp_tag4 != null)
                _jsp_tag4.release();
              if (_jsp_tag5 != null)
                _jsp_tag5.release();
              if (_jsp_tag6 != null)
                _jsp_tag6.release();
              if (_jsp_tag7 != null)
                _jsp_tag7.release();
              if (_jsp_tag8 != null)
                _jsp_tag8.release();
              if (_jsp_tag9 != null)
                _jsp_tag9.release();
              if (_jsp_tag10 != null)
                _jsp_tag10.release();
              if (_jsp_tag11 != null)
                _jsp_tag11.release();
              if (_jsp_tag12 != null)
                _jsp_tag12.release();
              if (_jsp_tag13 != null)
                _jsp_tag13.release();
              JspFactory.getDefaultFactory().releasePageContext(pageContext);
            }
          }

          private com.caucho.java.LineMap _caucho_line_map;
          private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

          public boolean _caucho_isModified()
          {
            if (_caucho_isDead)
              return true;
            if (com.caucho.util.CauchoSystem.getVersionId() != -2089842223)
              return true;
            for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
              com.caucho.vfs.Depend depend;
              depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
              if (depend.isModified())
                return true;
            }
            return false;
          }

          public long _caucho_lastModified()
          {
            return 0;
          }

          public com.caucho.java.LineMap _caucho_getLineMap()
          {
            return _caucho_line_map;
          }

          public void destroy()
          {
              _caucho_isDead = true;
              super.destroy();
          }

          public void init(com.caucho.java.LineMap lineMap,
                           com.caucho.vfs.Path appDir)
            throws javax.servlet.ServletException
          {
            com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
            com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
            mergePath.addMergePath(appDir);
            mergePath.addMergePath(resinHome);
            mergePath.addClassPath(getClass().getClassLoader());
            _caucho_line_map = new com.caucho.java.LineMap("_agencyList__jsp.java", "/administration/agencyList.jsp");
            _caucho_line_map.add(1, 1);
            _caucho_line_map.add(1, 40);
            _caucho_line_map.add(3, 41);
            _caucho_line_map.add(5, 42);
            _caucho_line_map.add(6, 51);
            _caucho_line_map.add(7, 59);
            _caucho_line_map.add(8, 68);
            _caucho_line_map.add(23, 77);
            _caucho_line_map.add(23, 88);
            _caucho_line_map.add(30, 99);
            _caucho_line_map.add(30, 104);
            _caucho_line_map.add(44, 115);
            _caucho_line_map.add(67, 117);
            _caucho_line_map.add(74, 122);
            _caucho_line_map.add(74, 136);
            _caucho_line_map.add(78, 141);
            _caucho_line_map.add(81, 145);
            _caucho_line_map.add(82, 147);
            _caucho_line_map.add(83, 149);
            _caucho_line_map.add(86, 154);
            _caucho_line_map.add(87, 156);
            _caucho_line_map.add(88, 158);
            _caucho_line_map.add(93, 166);
            _caucho_line_map.add(94, 170);
            _caucho_line_map.add(95, 174);
            _caucho_line_map.add(97, 178);
            _caucho_line_map.add(109, 194);
            _caucho_line_map.add(109, 205);
            _caucho_line_map.add(110, 216);
            _caucho_line_map.add(111, 220);
            _caucho_line_map.add(111, 224);
            com.caucho.vfs.Depend depend;
            depend = new com.caucho.vfs.Depend(appDir.lookup("administration/agencyList.jsp"), 1086643947000L, 4850L);
            _caucho_depends.add(depend);
          }

          protected void _caucho_clearDepends()
          {
            _caucho_depends.clear();
          }
          private static com.caucho.el.Expr _caucho_expr_0 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agencyListForm"), new com.caucho.el.StringLiteral("htmlData")), new com.caucho.el.StringLiteral("name"));
          private static com.caucho.el.Expr _caucho_expr_1 =
            new com.caucho.el.UnaryExpr(16, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agencyListBean"), new com.caucho.el.StringLiteral("list")));
          private static com.caucho.el.Expr _caucho_expr_2 =
            new com.caucho.el.EqExpr(6, new com.caucho.el.BinaryExpr(5, new com.caucho.el.BinaryExpr(1, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("status"), new com.caucho.el.StringLiteral("index")), new com.caucho.el.LongLiteral(1L)), new com.caucho.el.LongLiteral(2L)), new com.caucho.el.LongLiteral(0L));
          private static com.caucho.el.Expr _caucho_expr_3 =
            new com.caucho.el.EqExpr(7, new com.caucho.el.BinaryExpr(5, new com.caucho.el.BinaryExpr(1, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("status"), new com.caucho.el.StringLiteral("index")), new com.caucho.el.LongLiteral(1L)), new com.caucho.el.LongLiteral(2L)), new com.caucho.el.LongLiteral(0L));
          private static com.caucho.el.Expr _caucho_expr_4 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agency"), new com.caucho.el.StringLiteral("id"));
          private static com.caucho.el.Expr _caucho_expr_5 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agency"), new com.caucho.el.StringLiteral("company"));
          private static com.caucho.el.Expr _caucho_expr_6 =
            new com.caucho.el.BooleanExpr(12, new com.caucho.el.BooleanExpr(12, new com.caucho.el.EqExpr(6, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agency"), new com.caucho.el.StringLiteral("address")), new com.caucho.el.NullLiteral()), new com.caucho.el.EqExpr(6, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agency"), new com.caucho.el.StringLiteral("postalCode")), new com.caucho.el.NullLiteral())), new com.caucho.el.EqExpr(6, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agency"), new com.caucho.el.StringLiteral("city")), new com.caucho.el.NullLiteral()));
          private static com.caucho.el.Expr _caucho_expr_7 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agency"), new com.caucho.el.StringLiteral("address"));
          private static com.caucho.el.Expr _caucho_expr_8 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agency"), new com.caucho.el.StringLiteral("postalCode"));
          private static com.caucho.el.Expr _caucho_expr_9 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agency"), new com.caucho.el.StringLiteral("city"));
          private static com.caucho.el.Expr _caucho_expr_10 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agency"), new com.caucho.el.StringLiteral("phone"));
          private static com.caucho.el.Expr _caucho_expr_11 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agency"), new com.caucho.el.StringLiteral("fax"));
          private static com.caucho.el.Expr _caucho_expr_12 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agency"), new com.caucho.el.StringLiteral("email"));
          private static com.caucho.el.Expr _caucho_expr_13 =
            new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agency"), new com.caucho.el.StringLiteral("nbEmployees"));

          private static byte []_jsp_string0;
          private static byte []_jsp_string14;
          private static byte []_jsp_string18;
          private static byte []_jsp_string4;
          private static byte []_jsp_string1;
          private static byte []_jsp_string13;
          private static byte []_jsp_string22;
          private static byte []_jsp_string6;
          private static byte []_jsp_string15;
          private static byte []_jsp_string10;
          private static byte []_jsp_string3;
          private static byte []_jsp_string23;
          private static byte []_jsp_string5;
          private static byte []_jsp_string8;
          private static byte []_jsp_string20;
          private static byte []_jsp_string9;
          private static byte []_jsp_string7;
          private static byte []_jsp_string17;
          private static byte []_jsp_string19;
          private static byte []_jsp_string12;
          private static byte []_jsp_string16;
          private static byte []_jsp_string11;
          private static byte []_jsp_string2;
          private static byte []_jsp_string21;
          static {
            _jsp_string0 = "\n\n".getBytes();
            _jsp_string14 = "N/A".getBytes();
            _jsp_string18 = "</td>\n					<td>&nbsp;\n						<img src=\"/include/pictures/pencil.png\" alt=\"Modifier\" onclick=\"document.listForm.id.value='".getBytes();
            _jsp_string4 = "\n	\n		<form name=\"listForm\" action=\"DomainActionServlet\" method=\"POST\">\n			<input type=\"hidden\" name=\"domain\" value=\"agency\">\n			<input type=\"hidden\" name=\"action\">\n			<input type=\"hidden\" name=\"subAction\">\n			<input type=\"hidden\" name=\"id\">\n	\n		<br>\n				\n		<h1 class=\"title\">Agences&nbsp;&nbsp;:&nbsp;:&nbsp;&nbsp;Liste</h1>\n		\n		<div class=\"boxTitle\">&nbsp;&nbsp;Recherche par: </div>\n		<div class=\"boxCol\">\n			<p class=\"boxSearch\">Nom:&nbsp;<input type=\"text\" name=\"name\" length=\"30\" value=\"".getBytes();
            _jsp_string1 = "\n".getBytes();
            _jsp_string13 = "</td>\n					<td>".getBytes();
            _jsp_string22 = "\n			</table>\n		</div>\n		\n		<!-- multipage navigation -->\n		".getBytes();
            _jsp_string6 = "\n				<tr class=\"noresult\">\n					<td colspan=\"8\">Aucun r\u00e9sultat</td>\n				</tr>\n	".getBytes();
            _jsp_string15 = "\n       							".getBytes();
            _jsp_string10 = "\n				<tr class=\"result_odd\">\n			".getBytes();
            _jsp_string3 = "\n	\n	</head>\n	\n	<body>\n	\n		<!-- display header : company logo + menu + user info -->\n		".getBytes();
            _jsp_string23 = "\n		\n		</form>\n	<body>\n	\n</html>".getBytes();
            _jsp_string5 = "\"></p>\n		</div>\n		\n		\n		<div class=\"boxTitle\">&nbsp;&nbsp;Actions:</div>\n		<div class=\"boxCol\">\n			<p class=\"boxAction\"><a class=\"classicButtonBlue\" onclick=\"document.listForm.action.value='list'; document.listForm.subAction.value='init'; document.listForm.submit();\">&nbsp;[ rechercher ]&nbsp;</a></p>\n			<p class=\"boxAction\"><a class=\"classicButtonBlue\" onclick=\"document.listForm.action.value='add'; document.listForm.subAction.value='init'; document.listForm.submit();\">&nbsp;[ ajouter ]&nbsp;</a></p>\n			<p class=\"boxAction\"><a class=\"classicButtonBlue\" onclick=\"\">&nbsp;[ supprimer ]&nbsp;</a></p>\n		</div>\n		\n		<div class=\"boxResults\">\n			<table border=\"0\" width=\"100%\" cellpadding=\"0px\" cellspacing=\"0px\"> \n				<tr>\n					<th width=\"2%\">&nbsp;</th>\n					<th width=\"20%\">Agence</th>\n					<th width=\"30%\">Adresse</th>\n					<th width=\"10%\">T\u00e9l\u00e9phone</th>\n					<th width=\"10%\">Fax</th>\n					<th width=\"10%\">Email</th>\n					<th width=\"10%\">Nombre employ\u00e9s</th>\n					<th width=\"8%\">Actions</th>\n				</tr>\n".getBytes();
            _jsp_string8 = "\n			".getBytes();
            _jsp_string20 = "'; document.listForm.action.value='delete'; document.listForm.subAction.value='one'; document.listForm.submit();\"/>\n					</td>\n				</tr>\n			".getBytes();
            _jsp_string9 = " \n				<tr class=\"result_par\">\n			".getBytes();
            _jsp_string7 = "\n		".getBytes();
            _jsp_string17 = "\n					</td>\n					<td>".getBytes();
            _jsp_string19 = "'; document.listForm.action.value='update'; document.listForm.subAction.value='init'; document.listForm.submit();\"/>&nbsp;&nbsp;\n						<img src=\"/include/pictures/glass.png\" alt=\"Voir d\u00e9tail\">&nbsp;&nbsp;\n						<img src=\"/include/pictures/trash.png\" alt=\"Supprimer\" onclick=\"document.listForm.id.value='".getBytes();
            _jsp_string12 = "\"></td>\n					<td>".getBytes();
            _jsp_string16 = "\n           					".getBytes();
            _jsp_string11 = "\n					<td><input type=\"checkbox\" value=\"".getBytes();
            _jsp_string2 = "\n\n\n<?xml version=\"1\" encoding=\"ISO-8859-1\"?>\n<!DOCTYPE html PUBLIC \"- //w3c//DTD XHTML 1.0 Strict//EN\" \n\"http://www.w3.org/TR/xhtml11/DTD/xhtml11-strict.dtd\">\n\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n	<head>\n		<title>Liste des agences</title>\n		<link href=\"/include/style/styleList.css\" rel=\"stylesheet\" type=\"text/css\">\n		<link href=\"/include/style/global.css\" rel=\"stylesheet\" type=\"text/css\">\n		<link href=\"/include/style/header.css\" rel=\"stylesheet\" type=\"text/css\">\n		\n		<!-- create dynamic menu -->\n		".getBytes();
            _jsp_string21 = "\n	".getBytes();
          }
        }
