/*
 * JSP generated by Resin 2.1.12 (built Tue Dec  9 14:58:25 PST 2003)
 */

package _include._jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _header__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=iso-8859-1");
    org.apache.taglibs.standard.tag.el.core.OutTag _jsp_tag0 = null;
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      com.eurocash.data.administration.employee.EmployeeBean employeeBean;
      synchronized (session) {
        employeeBean = (com.eurocash.data.administration.employee.EmployeeBean) session.getAttribute("employeeBean");
        if (employeeBean == null) {
          employeeBean = new com.eurocash.data.administration.employee.EmployeeBean();
          session.setAttribute("employeeBean", employeeBean);
        }
      }
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      com.eurocash.menu.Tree menu;
      synchronized (application) {
        menu = (com.eurocash.menu.Tree) application.getAttribute("menu");
        if (menu == null) {
          menu = new com.eurocash.menu.Tree();
          application.setAttribute("menu", menu);
        }
      }
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      com.eurocash.data.administration.agency.AgenciesBean agenciesBean;
      synchronized (application) {
        agenciesBean = (com.eurocash.data.administration.agency.AgenciesBean) application.getAttribute("agenciesBean");
        if (agenciesBean == null) {
          agenciesBean = new com.eurocash.data.administration.agency.AgenciesBean();
          application.setAttribute("agenciesBean", agenciesBean);
        }
      }
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      _caucho_expr_0.print(pageContext.getWriteStream(), pageContext, true);
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      _caucho_expr_1.print(pageContext.getWriteStream(), pageContext, true);
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      _caucho_expr_2.print(pageContext.getWriteStream(), pageContext, true);
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_tag0 != null)
        _jsp_tag0.release();
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -2089842223)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_header__jsp.java", "/include/jsp/header.jsp");
    _caucho_line_map.add(1, 1);
    _caucho_line_map.add(1, 27);
    _caucho_line_map.add(3, 28);
    _caucho_line_map.add(5, 29);
    _caucho_line_map.add(6, 38);
    _caucho_line_map.add(7, 47);
    _caucho_line_map.add(11, 56);
    _caucho_line_map.add(17, 58);
    _caucho_line_map.add(17, 60);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("include/jsp/header.jsp"), 1087669006000L, 884L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }
  private static com.caucho.el.Expr _caucho_expr_0 =
    new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("agenciesBean"), new com.caucho.el.StringLiteral("agenciesMap")), new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("employeeBean"), new com.caucho.el.StringLiteral("agencyId"))), new com.caucho.el.StringLiteral("company"));
  private static com.caucho.el.Expr _caucho_expr_1 =
    new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("employeeBean"), new com.caucho.el.StringLiteral("lastName"));
  private static com.caucho.el.Expr _caucho_expr_2 =
    new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("employeeBean"), new com.caucho.el.StringLiteral("firstName"));

  private static byte []_jsp_string0;
  private static byte []_jsp_string3;
  private static byte []_jsp_string4;
  private static byte []_jsp_string5;
  private static byte []_jsp_string1;
  private static byte []_jsp_string2;
  static {
    _jsp_string0 = "\n\n".getBytes();
    _jsp_string3 = "\n	</div>\n	\n	<div class=\"boxHeaderTitle\">Projet Papyrus</div>\n\n	<div class=\"boxHeaderInfos\">\n		::".getBytes();
    _jsp_string4 = "&nbsp;".getBytes();
    _jsp_string5 = "::\n	</div>\n\n	\n</div>\n\n<!-- Display menu -->\n<div class=\"boxMenu\">\n	<script>\n		document.write(menuBar);	\n	</script>\n</div>\n".getBytes();
    _jsp_string1 = "\n".getBytes();
    _jsp_string2 = "\n\n<div class=\"boxContainer\">\n	<div class=\"boxHeaderVoid\">\n		Agence&nbsp;".getBytes();
  }
}
