/*
 * JSP generated by Resin 2.1.12 (built Tue Dec  9 14:58:25 PST 2003)
 */

package _include._jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _menu__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=iso-8859-1");
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      com.eurocash.data.administration.employee.EmployeeBean employeeBean;
      synchronized (session) {
        employeeBean = (com.eurocash.data.administration.employee.EmployeeBean) session.getAttribute("employeeBean");
        if (employeeBean == null) {
          employeeBean = new com.eurocash.data.administration.employee.EmployeeBean();
          session.setAttribute("employeeBean", employeeBean);
        }
      }
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      com.eurocash.menu.Tree menu;
      synchronized (application) {
        menu = (com.eurocash.menu.Tree) application.getAttribute("menu");
        if (menu == null) {
          menu = new com.eurocash.menu.Tree();
          application.setAttribute("menu", menu);
        }
      }
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((menu.toJavaScript(menu.getRoot(), employeeBean.getRightsId(), 0)));
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -2089842223)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_menu__jsp.java", "/include/jsp/menu.jsp");
    _caucho_line_map.add(1, 1);
    _caucho_line_map.add(1, 26);
    _caucho_line_map.add(3, 27);
    _caucho_line_map.add(4, 36);
    _caucho_line_map.add(20, 45);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("include/jsp/menu.jsp"), 1086213391000L, 800L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }

  private static byte []_jsp_string0;
  private static byte []_jsp_string2;
  private static byte []_jsp_string3;
  private static byte []_jsp_string1;
  static {
    _jsp_string0 = "\n\n".getBytes();
    _jsp_string2 = "\n\n<link href=\"/include/style/xmenu.css\" type=\"text/css\" rel=\"stylesheet\">\n<script src=\"/include/scripts/cssexpr.js\"></script>\n<script src=\"/include/scripts/xmenu.js\"></script>\n<script>\n	webfxMenuImagePath = \"/include/pictures/xmenu/\";\n	var menuBar = new WebFXMenuBar;\n	\n	menuBar.top = 90;\n	menuBar.left = 200;\n	menuBar.width = 300;\n	//menuBar.borderLeft = 300;\n	\n	\n	\n	".getBytes();
    _jsp_string3 = "\n	/*\n	submenu2.top = 500;\n	submenu2.left = 200;\n	submenu2.width = 50;\n	\n	menu3.width=50;\n	*/\n</script>".getBytes();
    _jsp_string1 = "\n".getBytes();
  }
}
