/*
 * JSP generated by Resin 2.1.12 (built Tue Dec  9 14:58:25 PST 2003)
 */

package _include._jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.eurocash.data.ItemListBean;

public class _multipage__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=iso-8859-1");
    org.apache.taglibs.standard.tag.el.core.IfTag _jsp_tag0 = null;
    org.apache.taglibs.standard.tag.el.core.OutTag _jsp_tag1 = null;
    org.apache.taglibs.standard.tag.el.core.IfTag _jsp_tag2 = null;
    org.apache.taglibs.standard.tag.el.core.OutTag _jsp_tag3 = null;
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
	/* get the request attribute corresponding to the current itemFormBean */
	String nameBean = request.getParameter("listBean");
	ItemListBean listBean = null;
	
	if (null != nameBean)
		listBean = (ItemListBean) session.getAttribute(nameBean);
	else
		return;
		
	/* put it into the current context */
	pageContext.setAttribute("listBean", listBean);
	pageContext.setAttribute("domain", request.getParameter("domain"));

      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      if (_caucho_expr_0.evalBoolean(pageContext)) {
        pageContext.write(_jsp_string2, 0, _jsp_string2.length);
        _caucho_expr_1.print(pageContext.getWriteStream(), pageContext, true);
        pageContext.write(_jsp_string3, 0, _jsp_string3.length);
        if (_caucho_expr_2.evalBoolean(pageContext)) {
          pageContext.write(_jsp_string4, 0, _jsp_string4.length);
          _caucho_expr_3.print(pageContext.getWriteStream(), pageContext, true);
          pageContext.write(_jsp_string5, 0, _jsp_string5.length);
          _caucho_expr_4.print(pageContext.getWriteStream(), pageContext, true);
          pageContext.write(_jsp_string6, 0, _jsp_string6.length);
        }
        pageContext.write(_jsp_string7, 0, _jsp_string7.length);
        if (_caucho_expr_5.evalBoolean(pageContext)) {
          pageContext.write(_jsp_string8, 0, _jsp_string8.length);
          _caucho_expr_6.print(pageContext.getWriteStream(), pageContext, true);
          pageContext.write(_jsp_string9, 0, _jsp_string9.length);
          _caucho_expr_7.print(pageContext.getWriteStream(), pageContext, true);
          pageContext.write(_jsp_string10, 0, _jsp_string10.length);
          _caucho_expr_3.print(pageContext.getWriteStream(), pageContext, true);
          pageContext.write(_jsp_string11, 0, _jsp_string11.length);
        }
        pageContext.write(_jsp_string12, 0, _jsp_string12.length);
        if (_caucho_expr_8.evalBoolean(pageContext)) {
          pageContext.write(_jsp_string13, 0, _jsp_string13.length);
          _caucho_expr_3.print(pageContext.getWriteStream(), pageContext, true);
          pageContext.write(_jsp_string5, 0, _jsp_string5.length);
          _caucho_expr_9.print(pageContext.getWriteStream(), pageContext, true);
          pageContext.write(_jsp_string6, 0, _jsp_string6.length);
        }
        pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      }
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_tag0 != null)
        _jsp_tag0.release();
      if (_jsp_tag1 != null)
        _jsp_tag1.release();
      if (_jsp_tag2 != null)
        _jsp_tag2.release();
      if (_jsp_tag3 != null)
        _jsp_tag3.release();
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -2089842223)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_multipage__jsp.java", "/include/jsp/multipage.jsp");
    _caucho_line_map.add(1, 1);
    _caucho_line_map.add(1, 31);
    _caucho_line_map.add(23, 52);
    _caucho_line_map.add(24, 54);
    _caucho_line_map.add(24, 56);
    _caucho_line_map.add(29, 60);
    _caucho_line_map.add(30, 62);
    _caucho_line_map.add(30, 64);
    _caucho_line_map.add(31, 66);
    _caucho_line_map.add(36, 70);
    _caucho_line_map.add(37, 72);
    _caucho_line_map.add(37, 74);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("include/jsp/multipage.jsp"), 1087430404000L, 1960L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }
  private static com.caucho.el.Expr _caucho_expr_0 =
    new com.caucho.el.UnaryExpr(14, new com.caucho.el.UnaryExpr(16, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("listBean"), new com.caucho.el.StringLiteral("list"))));
  private static com.caucho.el.Expr _caucho_expr_1 =
    new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("listBean"), new com.caucho.el.StringLiteral("nbResults"));
  private static com.caucho.el.Expr _caucho_expr_2 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.BooleanLiteral(true), new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("listBean"), new com.caucho.el.StringLiteral("previousPageOK")));
  private static com.caucho.el.Expr _caucho_expr_3 =
    new com.caucho.el.IdExpr("domain");
  private static com.caucho.el.Expr _caucho_expr_4 =
    new com.caucho.el.BinaryExpr(2, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("listBean"), new com.caucho.el.StringLiteral("currentPageIndex")), new com.caucho.el.LongLiteral(1L));
  private static com.caucho.el.Expr _caucho_expr_5 =
    new com.caucho.el.BooleanExpr(13, new com.caucho.el.EqExpr(6, new com.caucho.el.BooleanLiteral(true), new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("listBean"), new com.caucho.el.StringLiteral("previousPageOK"))), new com.caucho.el.EqExpr(6, new com.caucho.el.BooleanLiteral(true), new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("listBean"), new com.caucho.el.StringLiteral("nextPageOK"))));
  private static com.caucho.el.Expr _caucho_expr_6 =
    new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("listBean"), new com.caucho.el.StringLiteral("currentPageIndex"));
  private static com.caucho.el.Expr _caucho_expr_7 =
    new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("listBean"), new com.caucho.el.StringLiteral("maxNbPages"));
  private static com.caucho.el.Expr _caucho_expr_8 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.BooleanLiteral(true), new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("listBean"), new com.caucho.el.StringLiteral("nextPageOK")));
  private static com.caucho.el.Expr _caucho_expr_9 =
    new com.caucho.el.BinaryExpr(1, new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("listBean"), new com.caucho.el.StringLiteral("currentPageIndex")), new com.caucho.el.LongLiteral(1L));

  private static byte []_jsp_string1;
  private static byte []_jsp_string14;
  private static byte []_jsp_string12;
  private static byte []_jsp_string13;
  private static byte []_jsp_string11;
  private static byte []_jsp_string0;
  private static byte []_jsp_string8;
  private static byte []_jsp_string5;
  private static byte []_jsp_string6;
  private static byte []_jsp_string9;
  private static byte []_jsp_string3;
  private static byte []_jsp_string7;
  private static byte []_jsp_string10;
  private static byte []_jsp_string2;
  private static byte []_jsp_string4;
  static {
    _jsp_string1 = "\n\n".getBytes();
    _jsp_string14 = "\n</div>\n".getBytes();
    _jsp_string12 = "\n</div>\n<div class=\"navigationBox\">\n	&nbsp;\n	".getBytes();
    _jsp_string13 = "\n		<img src=\"/include/pictures/arrow_next.png\" alt=\"Page suivante\" onclick=\"window.location.href='/DomainActionServlet?domain=".getBytes();
    _jsp_string11 = "&action=list&subAction=goto&pageIndex=' + document.listForm.currentPageIndex.value;\">&nbsp;OK&nbsp;</a>\n	".getBytes();
    _jsp_string0 = "\n".getBytes();
    _jsp_string8 = "\n		<input type=\"int\" name=\"currentPageIndex\" maxlength=\"3\" size=\"4\" value=\"".getBytes();
    _jsp_string5 = "&action=list&subAction=goto&pageIndex=".getBytes();
    _jsp_string6 = "';\">\n	".getBytes();
    _jsp_string9 = "\">&nbsp;/".getBytes();
    _jsp_string3 = " -->\n<div class=\"navigationBox\">\n	&nbsp;\n	".getBytes();
    _jsp_string7 = "\n</div>\n<div class=\"navigationBoxMiddle\">\n	&nbsp;\n	".getBytes();
    _jsp_string10 = "&nbsp;&nbsp;&nbsp;\n		<a class=\"classicButtonGreen\" onclick=\"window.location.href='/DomainActionServlet?domain=".getBytes();
    _jsp_string2 = "\n<br><br>\n<!-- number of results = ".getBytes();
    _jsp_string4 = "\n		<img src=\"/include/pictures/arrow_previous.png\" alt=\"Page Pr\u00e9c\u00e9dente\" onclick=\"window.location.href='/DomainActionServlet?domain=".getBytes();
  }
}
